package org.pojoquery.dialects;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.pojoquery.DbContext;
import org.pojoquery.FieldMapping;
import org.pojoquery.SqlExpression;
import org.pojoquery.pipeline.AQTSchemaGenerator.DDLColumnMetadata;
import org.pojoquery.pipeline.SimpleFieldMapping;

/**
 * DbContext implementation for HSQLDB (HyperSQL Database).
 * Uses ANSI quoting style for identifiers.
 * Ideal for testing and embedded database scenarios.
 */
public class HsqldbDbContext implements DbContext {

    @Override
    public Dialect getDialect() {
        return Dialect.HSQLDB;
    }

    @Override
    public QuoteStyle getQuoteStyle() {
        return QuoteStyle.ANSI;
    }

    @Override
    public String quoteObjectNames(String... names) {
        StringBuilder ret = new StringBuilder();
        for (int i = 0; i < names.length; i++) {
            if (i > 0) {
                ret.append(".");
            }
            ret.append(QuoteStyle.ANSI.quote(names[i]));
        }
        return ret.toString();
    }

    @Override
    public String quoteAlias(String alias) {
        return QuoteStyle.ANSI.quote(alias);
    }

    @Override
    public FieldMapping getFieldMapping(Field f) {
        return new SimpleFieldMapping(f);
    }

	@Override
	public String getForeignKeyColumnType() {
		return "BIGINT";
	}

    @Override
    public String mapJavaTypeToSql(Class<?> type, DDLColumnMetadata colMeta) {

        if (type.equals(Long.class) || type.equals(long.class)) {
            return "BIGINT";
        }
        if (type.equals(Integer.class) || type.equals(int.class)) {
            return "INT";
        }
        if (type.equals(Short.class) || type.equals(short.class )) {
            return "SMALLINT";
        }
        if (type.equals(Byte.class) || type.equals(byte.class)) {
            return "TINYINT";
        }
        if (type.equals(Double.class) || type.equals(double.class)) {
            return "DOUBLE";
        }
        if (type.equals(Float.class) || type.equals(float.class)) {
            return "FLOAT";
        }
        if (type.equals(Boolean.class) || type.equals(boolean.class)) {
            return "BOOLEAN";
        }
        if (type.equals(BigDecimal.class)) {
            int precision = (colMeta != null) ? colMeta.precision() : 19;
            int scale = (colMeta != null) ? colMeta.scale() : 4;
            return "DECIMAL(" + precision + "," + scale + ")";
        }
        if (type.equals(BigInteger.class)) {
            return "BIGINT";
        }

        if (type.equals(String.class)) {
            if (colMeta != null && colMeta.isLob()) {
                return "CLOB";
            }
            int length = (colMeta != null) ? colMeta.length() : getDefaultVarcharLength();
            return "VARCHAR(" + length + ")";
        }

        if (type.equals(Date.class) || type.equals(LocalDateTime.class) || type.equals(Instant.class) || type.equals(java.sql.Timestamp.class)) {
            return "TIMESTAMP";
        }
        if (type.equals(LocalDate.class) || type.equals(java.sql.Date.class)) {
            return "DATE";
        }
        if (type.equals(LocalTime.class) || type.equals(java.sql.Time.class)) {
            return "TIME";
        }

        if (type.equals(byte[].class)) {
            return "BLOB";
        }

        if (type.isEnum()) {
            return "VARCHAR(" + getDefaultVarcharLength() + ")";
        }

        return "VARCHAR(" + getDefaultVarcharLength() + ")";
    }

    @Override
    public String getAutoIncrementSyntax() {
        return "GENERATED BY DEFAULT AS IDENTITY (START WITH 1)";
    }

    @Override
    public String getCreateTableSuffix() {
        return "";
    }

    @Override
    public int getStreamingFetchSize() {
        return 0; // HSQLDB default
    }

    @Override
    public SqlExpression jsonObject(List<JsonProperty> properties) {
        return jsonObject(properties, false);
    }

    /**
     * HSQLDB's JSON_ARRAYAGG parser does not accept a CASE returning JSON_OBJECT
     * (it collapses to VARCHAR and gets escaped) and does not allow FORMAT JSON
     * on its argument. So we keep a single JSON_OBJECT and push the polymorphism
     * into property values:
     * <pre>
     *   'subclassField': CASE WHEN &lt;condition&gt; THEN &lt;expr&gt; END   -- NULL otherwise
     * </pre>
     * The JSON_OBJECT uses ABSENT ON NULL so the irrelevant subclass properties
     * are stripped from the output. Note this also strips base properties whose
     * value is legitimately NULL.
     */
    @Override
    public SqlExpression jsonObjectWithVariants(List<JsonProperty> baseProperties, List<JsonVariant> variants) {
        if (variants.isEmpty()) {
            return jsonObject(baseProperties);
        }
        List<JsonProperty> merged = new ArrayList<>(baseProperties);
        for (JsonVariant variant : variants) {
            for (JsonProperty property : variant.properties()) {
                SqlExpression guarded = SqlExpression.implode("", List.of(
                        SqlExpression.sql("CASE WHEN "),
                        variant.condition(),
                        SqlExpression.sql(" THEN "),
                        property.value(),
                        SqlExpression.sql(" END")));
                merged.add(new JsonProperty(property.name(), guarded));
            }
        }
        return jsonObject(merged, true);
    }

    private SqlExpression jsonObject(List<JsonProperty> properties, boolean absentOnNull) {
        List<SqlExpression> parts = new ArrayList<>();
        for (JsonProperty property : properties) {
            parts.add(SqlExpression.implode("", List.of(
                    SqlExpression.sql("'" + DbContext.escapeSqlStringLiteral(property.name()) + "': "),
                    property.value())));
        }
        return SqlExpression.implode("", List.of(
                SqlExpression.sql("JSON_OBJECT(\n  "),
                SqlExpression.implode(",\n  ", parts),
                SqlExpression.sql((absentOnNull ? "\n  ABSENT ON NULL" : "") + "\n )")));
    }

    /**
     * HSQLDB rejects an untyped NULL in array element position, so callers must
     * pass typed expressions; {@code NULL ON NULL} is stated explicitly so a
     * future parser change to the standard's ABSENT ON NULL default cannot
     * silently drop a slot.
     */
    @Override
    public SqlExpression jsonArray(List<SqlExpression> elements) {
        return SqlExpression.implode("", List.of(
                SqlExpression.sql("JSON_ARRAY(\n  "),
                SqlExpression.implode(",\n  ", elements),
                SqlExpression.sql("\n  NULL ON NULL\n )")));
    }

    /** A length-less {@code VARCHAR} cast is accepted and never truncates. */
    @Override
    public SqlExpression castToStringExpression(SqlExpression value) {
        return SqlExpression.implode("", List.of(
                SqlExpression.sql("CAST("), value, SqlExpression.sql(" AS VARCHAR)")));
    }

    /** {@code FORMAT JSON} is not accepted in array element position on HSQLDB. */
    @Override
    public boolean jsonArrayNestsDocuments() {
        return false;
    }

    @Override
    public SqlExpression jsonValueRef(SqlExpression jsonValue) {
        return SqlExpression.implode("", List.of(jsonValue, SqlExpression.sql(" FORMAT JSON")));
    }

    @Override
    public String stringLiteralExpression(String value) {
        // Plain literals are CHAR-typed; a CASE over CHAR literals of different
        // lengths unifies to CHAR(max) and pads shorter values with spaces.
        return "CAST('" + DbContext.escapeSqlStringLiteral(value) + "' AS VARCHAR(" + Math.max(1, value.length()) + "))";
    }
}
