package org.pojoquery.integrationtest.db;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;
import java.util.Map;

import org.pojoquery.DbContext;
import org.pojoquery.FieldMapping;
import org.pojoquery.pipeline.SimpleFieldMapping;

/**
 * DbContext implementation for HSQLDB.
 * Uses QuoteStyle.NONE so identifiers are case-insensitive (stored as uppercase).
 */
public class HsqldbDbContext implements DbContext {

    @Override
    public String quoteObjectNames(String... names) {
        StringBuilder ret = new StringBuilder();
        for (int i = 0; i < names.length; i++) {
            if (i > 0) {
                ret.append(".");
            }
            // No quoting - identifiers will be case-insensitive
            ret.append(names[i]);
        }
        return ret.toString();
    }

    @Override
    public QuoteStyle getQuoteStyle() {
        return QuoteStyle.NONE;
    }

    @Override
    public String quoteAlias(String alias) {
        // Quote aliases with ANSI double quotes to preserve the dot separator
        // (e.g., "event.eventID") while keeping table/column names unquoted
        return "\"" + alias + "\"";
    }

    @Override
    public FieldMapping getFieldMapping(Field f) {
        return new SimpleFieldMapping(f);
    }

    @Override
    public String mapJavaTypeToSql(Class<?> type) {
        // Handle primitive types and wrappers
        if (type == Long.class || type == long.class) {
            return "BIGINT";
        }
        if (type == Integer.class || type == int.class) {
            return "INT";
        }
        if (type == Short.class || type == short.class) {
            return "SMALLINT";
        }
        if (type == Byte.class || type == byte.class) {
            return "TINYINT";
        }
        if (type == Double.class || type == double.class) {
            return "DOUBLE";
        }
        if (type == Float.class || type == float.class) {
            return "FLOAT";
        }
        if (type == Boolean.class || type == boolean.class) {
            return "BOOLEAN";
        }
        if (type == BigDecimal.class) {
            return "DECIMAL(19,4)";
        }
        if (type == BigInteger.class) {
            return "BIGINT";
        }

        // Date/Time types
        if (type == Date.class || type == LocalDateTime.class) {
            return "TIMESTAMP";
        }
        if (type == LocalDate.class) {
            return "DATE";
        }
        if (type == LocalTime.class) {
            return "TIME";
        }

        // String and text types
        if (type == String.class) {
            return "VARCHAR(" + getDefaultVarcharLength() + ")";
        }

        // Binary types
        if (type == byte[].class) {
            return "BLOB";
        }

        // Enum types - store as VARCHAR
        if (type.isEnum()) {
            return "VARCHAR(" + getDefaultVarcharLength() + ")";
        }

        // Map/JSON types - HSQLDB doesn't have native JSON, use CLOB
        if (Map.class.isAssignableFrom(type)) {
            return "CLOB";
        }

        // Default fallback
        return "VARCHAR(" + getDefaultVarcharLength() + ")";
    }

    @Override
    public String getAutoIncrementSyntax() {
        return "GENERATED BY DEFAULT AS IDENTITY (START WITH 1)";
    }

    @Override
    public String getTableSuffix() {
        // No engine specification for HSQLDB
        return "";
    }

    @Override
    public int getStreamingFetchSize() {
        // HSQLDB doesn't support Integer.MIN_VALUE like MySQL
        // Use 0 for default behavior
        return 0;
    }

    @Override
    public Dialect getDialect() {
        return Dialect.HSQLDB;
    }
}
