package org.pojoquery;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.BiFunction;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.stream.Stream;

import javax.sql.DataSource;

import org.hsqldb.jdbc.JDBCDataSource;
import org.junit.Assert;
import org.junit.Test;
import org.pojoquery.DbContext.Dialect;
import org.pojoquery.annotations.Id;
import org.pojoquery.annotations.Link;
import org.pojoquery.annotations.Table;
import org.pojoquery.integrationtest.UseDialect;
import org.pojoquery.internal.TableMapping;
import org.pojoquery.pipeline.DefaultSqlQuery;
import org.pojoquery.pipeline.PojoMetadata;
import org.pojoquery.pipeline.SqlQuery;
import org.pojoquery.pipeline.querytree.TableInfo;
import org.pojoquery.pipeline.querytree.transforms.AliasNaming;
import org.pojoquery.typemodel.FieldModel;
import org.pojoquery.typemodel.ReflectionFieldModel;
import org.pojoquery.typemodel.ReflectionTypeModel;
import org.pojoquery.typemodel.TypeModel;
import org.pojoquery.util.Strings;

@UseDialect(Dialect.HSQLDB)
public class TestAlternativeStructureForQueryTree {

	/**
	 * This test explores a clearer structure for the querytree
	 * strictly based on java properties.
	 * 
	 * An entity is a class mapped to a table.
	 * 
	 * Each java property transforms into one of:
	 * - ScalarValue: a primitive value or string (non-entity), a single column or SQL expression
	 * - EntityReference: a reference to another entity (many-to-one or one-to-one)
	 * - EntityCollection: a collection of entities (one-to-many)
	 * - ValueCollection: a collection or map of scalar values (non-entities) from a one-to-many join
	 * - JoinTableEntityCollection: a collection of entities through a join table (many-to-many)
	 * - JoinTableValueCollection: a collection of primitive values (non-entities) through a join table (many-to-many)
	 * - Embedding: an embedded entity
	 * - Transient: a field is not queried (not mapped to any column or join)
	 * 
	 * Single Table Inheritance adds Embeddings for superclasses and subclasses
	 * 
	 * Table per Subclass adds an EntityReference for its direct superclass and direct subclasses
	 * 
	 * Each of the non-scalar types (EntityReference, EntityCollection, JoinTableEntityCollection, Embedding) corresponds to a TableNode in the query tree, and can have child nodes for their properties.
	 */

	public sealed interface QueryNode 
		permits TableNode, ScalarNode, EmptyTableNode, EmptyFieldNode {
	}

	public sealed interface ScalarNode 
		extends QueryNode, FieldNode 
		permits PrimaryKeyField, ForeignKeyField, ScalarValue, ValueCollection, JoinTableValueCollection {
	}

	public non-sealed interface PrimaryKeyField extends ScalarNode {
		Boolean isAutoGenerated();
	}

	public non-sealed interface ForeignKeyField extends ScalarNode {
	}

	public sealed interface TableNode 
		extends QueryNode 
		permits Embedding, RootNode, EntityReference, EntityCollection, JoinTableEntityCollection, TPSSubClassNode, TPSSuperClassNode {
		String alias();
		TypeModel type();
		TableInfo tableInfo();
		List<QueryNode> children();

		TableNode withChildren(List<? extends QueryNode> newChildren);
	}

	public non-sealed interface Embedding 
		extends TableNode {
		String sourceAlias();
	}

	public non-sealed interface TPSSubClassNode
		extends TableNode, JoinOne {
	}

	public non-sealed interface TPSSuperClassNode
		extends TableNode, JoinOne {
	}

	// STINode = Single Table Inheritance node, represents a class in the STI hierarchy. It has an alias and type, but shares the same table as its parent (so no join).
	public interface STINode
		extends Embedding {
		Object discriminatorValue();
		String discriminatorColumn();
	}

	public interface FieldNode {
		String columnName();
		FieldModel field();
	}
	
	public non-sealed interface EmptyFieldNode extends QueryNode {
		FieldModel field();
	}

	public record EmptyTableNode(String alias, TypeModel type, TableInfo tableInfo) implements QueryNode {
	}

	public record RootNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children) implements TableNode {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new RootNode(alias, type, tableInfo, List.copyOf(newChildren));
		}

		public RootNode fromEmptyTableNode(EmptyTableNode empty, List<QueryNode> children) {
			return new RootNode(empty.alias, empty.type, empty.tableInfo, List.copyOf(children));
		}
	}

	public record EmbeddedEntity(String alias, TypeModel type, String sourceAlias, TableInfo tableInfo, List<QueryNode> children) implements Embedding {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EmbeddedEntity(alias, type, sourceAlias, tableInfo, List.copyOf(newChildren));
		}
	}

	public record ScalarValue(FieldModel field, String columnName, SqlExpression expression) implements ScalarNode {

		public ScalarValue withExpression(SqlExpression sql) {
			return new ScalarValue(field, columnName, sql);
		}
	}

	public record PrimaryKey(FieldModel field, String columnName, SqlExpression expression, Boolean isAutoGenerated) implements PrimaryKeyField {
		public PrimaryKey withExpression(SqlExpression sql) {
			return new PrimaryKey(field, columnName, sql, isAutoGenerated);
		}

		public PrimaryKey setAutoGenerated(boolean b) {
			return new PrimaryKey(field, columnName, expression, b);
		}
	}

	public sealed interface Join permits JoinOne, JoinMany {
		String parentAlias();
		ForeignKeyInfo join();
		QueryNode withJoin(ForeignKeyInfo newJoin);
	}

	public sealed interface JoinMany extends FieldNode, Join {
		/** foreign key column in the child table
		 * references id column in parent table.
		 */
	}

	public sealed interface JoinOne extends FieldNode, Join {
		/** foreign key column in the parent table
		 * references id column in child table.
		 */
		
	}

	public non-sealed interface ValueCollection extends ScalarNode, JoinMany {
		SqlExpression expression();
	}

	public record JoinTableInfo (TableInfo tableInfo, String joinTableAlias) {
	}

	public record ForeignKeyInfo(TableInfo referringTable, String referringAlias, TableInfo targetTable, String targetAlias, FieldModel foreignKeyField, String fkColumnName, FieldModel idField, String idColumnName, SqlExpression joinCondition) {

		public ForeignKeyInfo {
			Objects.requireNonNull(idField, "idField must not be null");
    	}

		private static ForeignKeyInfo fkInParent(TableInfo parentTable, String parentAlias, TableInfo childTable, String childAlias, FieldModel foreignKeyField, FieldModel idField) {
			return new ForeignKeyInfo(parentTable, parentAlias, childTable, childAlias, foreignKeyField, null, idField, null, null);
		}

		private static ForeignKeyInfo fkInChild(TableInfo parentTable, String parentAlias, TableInfo childTable, String childAlias, FieldModel idField) {
			return new ForeignKeyInfo(childTable, childAlias, parentTable, parentAlias, null, null, idField, null, null);
		}

		public ForeignKeyInfo withJoinCondition(SqlExpression joinCondition) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField, fkColumnName, idField, idColumnName, joinCondition);
		}

		public ForeignKeyInfo withFkColumnName(String fkColumnName) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField, fkColumnName, idField, idColumnName, joinCondition);
		}

		public ForeignKeyInfo withIdColumnName(String idColumnName) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField, fkColumnName, idField, idColumnName, joinCondition);
		}
	}

	public record JoinTableJoin(JoinTableInfo joinTableInfo, ForeignKeyInfo parentKey, ForeignKeyInfo childKey) {

		public JoinTableJoin withJoinTableInfo(JoinTableInfo joinTableInfo) {
			return new JoinTableJoin(joinTableInfo, parentKey, childKey);
		}

		public JoinTableJoin withJoinForeignKeyInfo(ForeignKeyInfo parentKey, ForeignKeyInfo childKey) {
			return new JoinTableJoin(joinTableInfo, parentKey, childKey);
		}

	}

	public sealed interface HasJoinTableJoin {
		JoinTableJoin join();
		QueryNode withJoinTableJoin(JoinTableJoin joinTableJoin);
	}

	public record JoinTableEntityCollection 
		(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children, FieldModel field, JoinTableJoin join, String parentAlias)
		implements TableNode, HasJoinTableJoin {

		static QueryNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias, TypeModel componentType,
				TableInfo tableInfo, JoinTableJoin join, String parentAlias) {
			return new JoinTableEntityCollection(
				alias,
				componentType,
				tableInfo,
				null,
				emptyFieldNode.field(),
				join,
				parentAlias
			);
		}

		@Override
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new JoinTableEntityCollection(alias, type, tableInfo, List.copyOf(newChildren), field, join, parentAlias);
		}

		public JoinTableEntityCollection withJoinTableJoin(JoinTableJoin joinTableJoin) {
			return new JoinTableEntityCollection(alias, type, tableInfo, children, field, joinTableJoin, parentAlias);
		}

	}

	public non-sealed interface JoinTableValueCollection extends ScalarNode, HasJoinTableJoin {
		String[] fieldsToSelect();
		Function<Object[], Object> valueMapper();
	}

// EntityReference
// EntityCollection
// ValueCollection = EntityCollection with projection
// JoinTableEntityCollection
// JoinTableValueCollection = JoinTableEntityCollection with projection
// Embedding

// Superclasses zijn EntityReference of Embedded

// EntityReference heeft een field en columnName

	// record RootNodeImpl(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children) 
	// 	implements RootNode {
	// 		public RootNodeImpl withChildren(List<? extends QueryNode> newChildren) {
	// 			return new RootNodeImpl(alias, type, tableInfo, List.copyOf(newChildren));
	// 		}
	// 	}
	
	// record TableNodeImpl(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children) implements TableNode {
	// 	public TableNode withChildren(List<? extends QueryNode> newChildren) {
	// 		return new TableNodeImpl(alias, type, tableInfo, List.copyOf(newChildren));
	// 	}
	// }

	public record EmptyFieldNodeImpl(FieldModel field) implements EmptyFieldNode {}

	// record EmptyTableNodeImpl(String alias, TypeModel type, TableInfo tableInfo) implements EmptyTableNode {
	// 	public TableNodeImpl withChildren(List<? extends QueryNode> newChildren) {
	// 		return new TableNodeImpl(alias, type, tableInfo, List.copyOf(newChildren));
	// 	}
	// }

	record EntityReference(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children, FieldModel field, String parentAlias, String columnName, ForeignKeyInfo join) 
		implements TableNode, JoinOne {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EntityReference(alias, type, tableInfo, List.copyOf(newChildren), field, parentAlias, columnName, join);
		}

		public static EntityReference fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
				TableInfo determinTableInfo, FieldModel field, String parentAlias, ForeignKeyInfo join) {
			return new EntityReference(alias, field.getType(), determinTableInfo, null, field, parentAlias, null, join);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, newJoin.fkColumnName, newJoin);
		}

	}

	public record EntityCollection(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children, FieldModel field, String parentAlias, String columnName, ForeignKeyInfo join) 
		implements TableNode, JoinMany {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EntityCollection(alias, type, tableInfo, List.copyOf(newChildren), field, parentAlias, columnName, join);
		}

		public static TableNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
				TypeModel componentType, TableInfo tableInfo, String parentAlias, ForeignKeyInfo join) {
			return new EntityCollection(alias, componentType, tableInfo, null, emptyFieldNode.field(), parentAlias, null, join);
		}
		
		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new EntityCollection(alias, type, tableInfo, children, field, parentAlias, columnName, newJoin);
		}
	}

	@Table("person")
	static class Person {
		@Id
		Long id;
		String name;
	}

	@Table("comment")
	static class Comment {
		@Id
		Long id;
		String content;
	}


	@Table("category")
	static class Category {
		@Id
		Long id;
		String name;
	}

	@Table("article")
	static class ArticleDetail {
		@Id
		Long id;
		String title;
		Person author;
		List<Comment> comments;
		@Link(linktable = "article_category")
		List<Category> categories;
	}

	public QueryNode addDeclaredFields(QueryNode node) {
		return (node instanceof TableNode tableNode && tableNode.children() == null) ? 
			tableNode.withChildren(getFieldsOfEntity(tableNode.type()).stream()
				.map(f -> new EmptyFieldNodeImpl(f))
				.toList())
			:
			node;
	}

	private List<FieldModel> getFieldsOfEntity(TypeModel type) {
		List<TableMapping> mapping = PojoMetadata.determineTableMapping(type);
		return mapping.get(mapping.size() - 1).getFields().stream()
			.filter(f -> !PojoMetadata.isTransient(f))
			.toList();
	}

	private <C extends QueryNode> QueryNode transformChildren(QueryNode node, Predicate<QueryNode> childCondition, BiFunction<TableNode, C, QueryNode> transform) {
		return node instanceof TableNode parentNode && parentNode.children() != null ? 
			parentNode.withChildren(parentNode.children().stream()
				.map(child -> childCondition.test(child) ? transform.apply(parentNode, (C) child) : child)
				.toList())
			:
			node;
	}

	public QueryNode addEntityReferences(QueryNode node) {
		return transformChildren(node, 
			child -> child instanceof EmptyFieldNode emptyFieldNode && isEntity(emptyFieldNode.field().getType()),
			(TableNode parentNode, EmptyFieldNode emptyFieldNode) -> {
				String alias = AliasNaming.childAlias(
						node instanceof RootNode, 
						parentNode.alias(), 
						emptyFieldNode.field().getName());

				TypeModel referencedType = emptyFieldNode.field().getType();

				FieldModel childIdField = PojoMetadata.determineIdField(referencedType);

				return EntityReference.fromEmptyFieldNode(
						emptyFieldNode,
						alias,
						determinTableInfo(referencedType),
						emptyFieldNode.field(),
						parentNode.alias(),
						ForeignKeyInfo.fkInParent(parentNode.tableInfo(), parentNode.alias(), determinTableInfo(referencedType), alias, emptyFieldNode.field(), childIdField)
				);
			}
		);
	}


	public QueryNode addEntityCollections(QueryNode node) {
		return transformChildren(node,
			child -> child instanceof EmptyFieldNode emptyFieldNode && 
					isEntityCollection(emptyFieldNode.field().getType()),
			(TableNode parentNode, EmptyFieldNode emptyFieldNode) -> {
				TypeModel componentType = getCollectionComponentType(emptyFieldNode.field().getType());
				String alias = AliasNaming.childAlias(node instanceof RootNode, parentNode.alias(), emptyFieldNode.field().getName());
				TableInfo tableInfo = determinTableInfo(componentType);

				FieldModel idField = PojoMetadata.determineIdField(componentType);
				ForeignKeyInfo join = ForeignKeyInfo.fkInChild(parentNode.tableInfo(), parentNode.alias(), tableInfo, alias, idField);
				return EntityCollection.fromEmptyFieldNode(emptyFieldNode, alias, componentType, tableInfo, parentNode.alias(), join);
			}
		);
	}

	public QueryNode addJointableEntityCollections(QueryNode node) {
		return transformChildren(node,
			child -> child instanceof EmptyFieldNode emptyFieldNode && 
					isEntityCollection(emptyFieldNode.field().getType()) &&
					!Strings.isNullOrEmpty(emptyFieldNode.field().getAnnotationAttributeValue(Link.class, "linktable", String.class)),
			(TableNode parentNode, EmptyFieldNode emptyFieldNode) -> {
				TypeModel componentType = getCollectionComponentType(emptyFieldNode.field().getType());
				String alias = AliasNaming.childAlias(node instanceof RootNode, parentNode.alias(), emptyFieldNode.field().getName());
				TableInfo tableInfo = determinTableInfo(componentType);

				String linkTableName = emptyFieldNode.field().getAnnotationAttributeValue(Link.class, "linktable", String.class);
				String linkTableSchema = emptyFieldNode.field().getAnnotationAttributeValue(Link.class, "linkschema", String.class);

				String joinTableAlias = AliasNaming.childAlias(false, alias, linkTableName);

				TableInfo joinTable = new TableInfo(linkTableSchema.isEmpty() ? null : linkTableSchema, linkTableName);
				JoinTableInfo joinTableInfo = new JoinTableInfo(
					joinTable,
					joinTableAlias
				);

				JoinTableJoin join = new JoinTableJoin(
					joinTableInfo,
					ForeignKeyInfo.fkInChild(parentNode.tableInfo(), parentNode.alias(), joinTable, joinTableAlias, PojoMetadata.determineIdField(parentNode.type())),
					ForeignKeyInfo.fkInChild(tableInfo, alias, joinTable, joinTableAlias, PojoMetadata.determineIdField(componentType))
				);
				return JoinTableEntityCollection.fromEmptyFieldNode(emptyFieldNode, alias, componentType, tableInfo, join, parentNode.alias());
			}
		);
	}

	public QueryNode addIdFields(QueryNode node) {
		return transformChildren(node, 
			child -> child instanceof EmptyFieldNode emptyFieldNode && emptyFieldNode.field().getAnnotation(Id.class).isPresent(), 
			(TableNode parentNode, EmptyFieldNode emptyFieldNode) -> {
				FieldModel idField = emptyFieldNode.field();
				return new PrimaryKey(idField, idField.getName(), null, null);
			}
		);
	}

	public QueryNode addScalarValues(QueryNode node) {
		return node instanceof TableNode parentNode && parentNode.children() != null ? 
			parentNode.withChildren(parentNode.children().stream()
				.map(child -> (child instanceof EmptyFieldNode emptyFieldNode) ? 
					new ScalarValue(emptyFieldNode.field(), emptyFieldNode.field().getName(), null) :
					child
				)
				.toList())
			:
			node;
	}

	public QueryNode applyDefaultIdFieldNames(QueryNode node) {
		if (node instanceof HasJoinTableJoin jtj && (jtj.join().parentKey().idColumnName == null || jtj.join().childKey().idColumnName == null)) {
			ForeignKeyInfo parentKey = jtj.join().parentKey();
			parentKey = parentKey.idColumnName == null ? 
				parentKey.withIdColumnName(parentKey.idField().getName()) : 
				parentKey;
			ForeignKeyInfo childKey = jtj.join().childKey();
			childKey = childKey.idColumnName == null ? 
				childKey.withIdColumnName(childKey.idField().getName()) :
				childKey;

			return jtj.withJoinTableJoin(jtj.join().withJoinForeignKeyInfo(
				parentKey.withIdColumnName(parentKey.idField().getName()),
				childKey.withIdColumnName(childKey.idField().getName())
			));
		} else if (node instanceof Join join && join.join().idColumnName() == null) {
			ForeignKeyInfo fk = join.join();
			return join.withJoin(fk.withIdColumnName(fk.idField().getName()));
		}

		return node;
	}

	public QueryNode applyDefaultForeignKeyColumnNames(QueryNode node) {
		if (node instanceof HasJoinTableJoin jtj && jtj.join().childKey().fkColumnName() == null && jtj.join().parentKey().fkColumnName() == null) {
			// Default foreign key column names for join tables are [target tablename]_id
			JoinTableJoin join = jtj.join();
			String parentFkColumn = join.parentKey().targetTable().tableName() + "_id";
			String childFkColumn = join.childKey().targetTable().tableName() + "_id";
			return jtj.withJoinTableJoin(join.withJoinForeignKeyInfo(
				join.parentKey().withFkColumnName(parentFkColumn),
				join.childKey().withFkColumnName(childFkColumn)
			));
		} else if (node instanceof JoinOne join && join.join().fkColumnName() == null) {
			ForeignKeyInfo fk = join.join();
			String fkColumnName = fk.foreignKeyField().getName() + "_id";
			return join.withJoin(fk.withFkColumnName(fkColumnName));
		} else if (node instanceof JoinMany join && join.join().fkColumnName() == null) {
			ForeignKeyInfo fk = join.join();
			String fkColumnName = fk.targetTable().tableName() + "_id";
			return join.withJoin(fk.withFkColumnName(fkColumnName));
		}

		return node;
	}

	public QueryNode applyDefaultScalarExpressions(QueryNode node) {
		return transformChildren(node, 
			child -> child instanceof ScalarValue scalar && scalar.expression() == null,
			(TableNode parentNode, ScalarValue scalar) -> 
				scalar.withExpression(SqlExpression.sql("{" + parentNode.alias() + "." + scalar.field().getName() + "}"))
		);
	}

	public QueryNode applyDefaultJoinConditions(QueryNode node) {
		if (node instanceof Join join && join.join().joinCondition() == null) {
			ForeignKeyInfo fk = join.join();
			SqlExpression joinCondition = SqlExpression.sql("{" + fk.referringAlias() + "." + fk.fkColumnName() + "} = {" + fk.targetAlias() + "." + fk.idColumnName() + "}");
			ForeignKeyInfo newJoin = fk.withJoinCondition(joinCondition);
			return join.withJoin(newJoin);
		} else if (node instanceof HasJoinTableJoin jtj && jtj.join().parentKey().joinCondition() == null && jtj.join().childKey().joinCondition() == null) {
			ForeignKeyInfo parentKey = jtj.join().parentKey();
			ForeignKeyInfo childKey = jtj.join().childKey();
			SqlExpression parentJoinCondition = SqlExpression.sql("{" + parentKey.referringAlias() + "." + parentKey.fkColumnName() + "} = {" + parentKey.targetAlias() + "." + parentKey.idColumnName() + "}");
			SqlExpression childJoinCondition = SqlExpression.sql("{" + childKey.referringAlias() + "." + childKey.fkColumnName() + "} = {" + childKey.targetAlias() + "." + childKey.idColumnName() + "}");
			JoinTableJoin newJoin = jtj.join().withJoinForeignKeyInfo(
				parentKey.withJoinCondition(parentJoinCondition),
				childKey.withJoinCondition(childJoinCondition)
			);
			return jtj.withJoinTableJoin(newJoin);
		}
		return node;
	}

	public QueryNode makeSingleIdFieldsAutoIncrement(QueryNode node) {
		return transformChildren(node, 
			child -> child instanceof PrimaryKey pk && pk.isAutoGenerated() == null,
			(TableNode parentNode, PrimaryKey pk) -> 
				parentNode.children().stream().filter(c -> c instanceof PrimaryKey).count() == 1 ? pk.setAutoGenerated(true) : pk.setAutoGenerated(false)
		);
	}

	private boolean isEntity(TypeModel type) {
		return PojoMetadata.determineTableMapping(type).size() > 0;
	}

	private boolean isEntityCollection(TypeModel type) {
		return type.getArrayComponentType() != null && isEntity(type.getArrayComponentType()) ||
			type.getTypeArgument() != null && isEntity(type.getTypeArgument());
	}

	private TypeModel getCollectionComponentType(TypeModel type) {
		if (type.getArrayComponentType() != null) {
			return type.getArrayComponentType();
		} else if (type.getTypeArgument() != null) {
			return type.getTypeArgument();
		} else {
			throw new IllegalArgumentException("Not a collection type: " + type);
		}
	}

	private void toSql(TableNode node, SqlQuery<?> sqlQuery) {
		if (node instanceof RootNode) {
			sqlQuery.setTable(node.tableInfo().schemaName(), node.tableInfo().tableName());
		}
		// sqlQuery.addField(SqlExpression.sql("{" + node.alias() + ".id}")); // select id by default for root
		for (QueryNode child : node.children()) {
			if (child instanceof ScalarValue scalar) {
				sqlQuery.addField(scalar.expression(), node.alias() + "." + scalar.field().getName());
			} else if (child instanceof EntityReference ref) {
				sqlQuery.addJoin(SqlQuery.JoinType.LEFT, ref.tableInfo().tableName(), ref.alias(), ref.join().joinCondition());
				toSql((TableNode) ref, sqlQuery);
			} else if (child instanceof EntityCollection col) {
				sqlQuery.addJoin(SqlQuery.JoinType.LEFT, col.tableInfo().tableName(), col.alias(), col.join().joinCondition());
				toSql((TableNode) col, sqlQuery);
			} else if (child instanceof JoinTableEntityCollection jte) {
				sqlQuery.addJoin(SqlQuery.JoinType.LEFT, jte.join().joinTableInfo().tableInfo().tableName(), jte.join().joinTableInfo().joinTableAlias(), jte.join().parentKey().joinCondition());
				sqlQuery.addJoin(SqlQuery.JoinType.LEFT, jte.tableInfo().tableName(), jte.alias(), jte.join().childKey().joinCondition());
				toSql((TableNode) jte, sqlQuery);
			}
		}
	}

	public record DDLTable(TableInfo tableKey, List<DDLColumn> primaryKeyColumns) {
	}

	public record DDLColumn(DDLColumnKey columnKey, FieldModel field) {
	}

	public record DDLColumnKey(TableInfo tableKey, String columnName) {
	}

	public record DDLForeignKey(DDLColumnKey referringColumn, DDLColumnKey referencedIdColumn) {
	}
	public record DDLForeignKeyKey(DDLColumnKey referringColumn) {
	}

	interface DDLCollector {
		void registerTable(TableInfo tableKey, List<DDLColumn> primaryKeyColumns);
		void registerColumn(TableInfo table, String columnName, FieldModel field);
		void registerForeignKey(ForeignKeyInfo foreignKeyInfo);
	}

	private class DDLCollectorImpl implements DDLCollector {
		private HashMap<TableInfo, DDLTable> tables = new LinkedHashMap<>();
		private HashMap<DDLColumnKey, DDLColumn> columns = new LinkedHashMap<>();
		private HashMap<DDLColumnKey, List<FieldModel>> definingFields = new HashMap<>();
		private HashSet<DDLColumnKey> implicitForeignKeyColumns = new HashSet<>();
		private HashMap<DDLForeignKeyKey, DDLForeignKey> foreignKeys = new LinkedHashMap<>();
		@Override
		public void registerTable(TableInfo tableKey, List<DDLColumn> primaryKeyColumns) {
			tables.put(tableKey, new DDLTable(tableKey, primaryKeyColumns));
		}
		
		@Override
		public void registerColumn(TableInfo table, String columnName, FieldModel field) {
			// System.out.println("COLUMN: " + table.tableName() + "." + columnName + " Field: " + (field != null ? field.getName() : "[implicit foreign key]"));
			DDLColumnKey key = new DDLColumnKey(table, columnName);
			columns.put(key, new DDLColumn(key, field));
			if (field != null) {
				definingFields.computeIfAbsent(key, k -> new ArrayList<>()).add(field);
			} else {
				implicitForeignKeyColumns.add(key);
			}
		}

		@Override
		public void registerForeignKey(ForeignKeyInfo foreignKeyInfo) {
			DDLColumnKey ddlColumnKey = new DDLColumnKey(foreignKeyInfo.referringTable(), foreignKeyInfo.fkColumnName());
			registerColumn(foreignKeyInfo.referringTable(), foreignKeyInfo.fkColumnName(), foreignKeyInfo.foreignKeyField());
			foreignKeys.put(new DDLForeignKeyKey(ddlColumnKey), 
				new DDLForeignKey(ddlColumnKey, new DDLColumnKey(foreignKeyInfo.targetTable(), foreignKeyInfo.idColumnName()))
			);
		}
	}

	private List<String> generateCreateSchemaDDL(DbContext dbContext, RootNode... entities) {
		DDLCollectorImpl collector = new DDLCollectorImpl();
		for (RootNode entity : entities) {
			collectDDLForEntity(entity, collector);
		}
		
		List<String> statements = new ArrayList<>();
		
		// Generate CREATE TABLE statements
		for (DDLTable table : collector.tables.values()) {
			StringBuilder sb = new StringBuilder();
			sb.append("CREATE TABLE ");
			sb.append(dbContext.getQuoteStyle().quote(table.tableKey().tableName()));
			sb.append(" (\n");
			
			// Get columns for this table
			List<DDLColumn> tableColumns = collector.columns.values().stream()
				.filter(col -> col.columnKey().tableKey().equals(table.tableKey()))
				.toList();
			
			List<String> columnDefs = new ArrayList<>();
			for (DDLColumn col : tableColumns) {
				StringBuilder colDef = new StringBuilder();
				colDef.append("  ");
				colDef.append(dbContext.getQuoteStyle().quote(col.columnKey().columnName()));
				colDef.append(" ");
				
				// Determine SQL type
				if (col.field() != null) {
					boolean isAutoIncrement = table.primaryKeyColumns().contains(col) &&
						(col.field().getType().isSameType(new ReflectionTypeModel(Long.class)) || 
						col.field().getType().isSameType(new ReflectionTypeModel(long.class)));
					
					if (isAutoIncrement) {
						colDef.append(dbContext.getAutoIncrementKeyColumnType());
						colDef.append(" ");
						colDef.append(dbContext.getAutoIncrementSyntax());
					} else if (collector.foreignKeys.containsKey(new DDLForeignKeyKey(col.columnKey()))) {
						colDef.append(dbContext.getForeignKeyColumnType());
					} else {
						colDef.append(dbContext.mapJavaTypeToSql(col.field()));
					}
				} else {
					// Implicit foreign key column (from join table) - use BIGINT by default
					colDef.append(dbContext.getForeignKeyColumnType());
				}
				columnDefs.add(colDef.toString());
			}
			
			// Add primary key constraint if there are primary key columns
			if (!table.primaryKeyColumns().isEmpty()) {
				String pkColumns = table.primaryKeyColumns().stream()
					.map(pk -> dbContext.getQuoteStyle().quote(pk.columnKey().columnName()))
					.reduce((a, b) -> a + ", " + b)
					.orElse("");
				columnDefs.add("  PRIMARY KEY (" + pkColumns + ")");
			}
			
			sb.append(String.join(",\n", columnDefs));
			sb.append("\n)");
			statements.add(sb.toString());
		}
		
		// Generate ALTER TABLE statements for foreign keys
		for (DDLForeignKey fk : collector.foreignKeys.values()) {
			StringBuilder sb = new StringBuilder();
			sb.append("ALTER TABLE ");
			sb.append(dbContext.getQuoteStyle().quote(fk.referringColumn().tableKey().tableName()));
			sb.append(" ADD CONSTRAINT ");
			sb.append(dbContext.getQuoteStyle().quote("fk_" + fk.referringColumn().tableKey().tableName() + "_" + fk.referringColumn().columnName()));
			sb.append(" FOREIGN KEY (");
			sb.append(dbContext.getQuoteStyle().quote(fk.referringColumn().columnName()));
			sb.append(") REFERENCES ");
			sb.append(dbContext.getQuoteStyle().quote(fk.referencedIdColumn().tableKey().tableName()));
			sb.append(" (");
			sb.append(dbContext.getQuoteStyle().quote(fk.referencedIdColumn().columnName()));
			sb.append(")");
			statements.add(sb.toString());
		}
		
		return statements;
	}

	private void collectDDLForEntity(TableNode entity, DDLCollector collector) {
		TableInfo tableKey = new TableInfo(entity.tableInfo().schemaName(), entity.tableInfo().tableName());
		List<DDLColumn> primaryKeyColumns = entity.children().stream()
			.filter(child -> child instanceof PrimaryKey)
			.map(child -> (PrimaryKey) child)
			.map(pk -> new DDLColumn(new DDLColumnKey(tableKey, pk.columnName()), pk.field())) // placeholder type
			.toList();
		collector.registerTable(tableKey, primaryKeyColumns);

		for (QueryNode child : entity.children()) {
			if (child instanceof ScalarValue scalar) {
				collector.registerColumn(tableKey, scalar.columnName(), scalar.field());
			} else if (child instanceof PrimaryKeyField pkField) {
				collector.registerColumn(tableKey, pkField.columnName(), pkField.field());
			} else if (child instanceof Join ref) {
				collectDDLForEntity((TableNode)ref, collector);
				ForeignKeyInfo joinInfo = ref.join();
				collector.registerForeignKey(joinInfo);
			} else if (child instanceof JoinTableEntityCollection jte) {
				collectDDLForEntity(jte, collector);
				collector.registerTable(jte.join().joinTableInfo().tableInfo, List.of());
				collector.registerColumn(jte.join().joinTableInfo().tableInfo, jte.join().parentKey().fkColumnName(), null);
				collector.registerColumn(jte.join().joinTableInfo().tableInfo, jte.join().childKey().fkColumnName(), null);
				collector.registerForeignKey(jte.join().parentKey());
				collector.registerForeignKey(jte.join().childKey());
			}
		}
	}

	private RootNode buildQueryTreeForType(Class<?> clz) {
		ReflectionTypeModel rootType = new ReflectionTypeModel(clz);
		TableInfo tableInfo = determinTableInfo(rootType);
		QueryNode newTree = new RootNode(tableInfo.tableName(), rootType, tableInfo, null);
		QueryNode oldTree = null;
		do {
			oldTree = newTree;
			newTree = Optional.<QueryNode>ofNullable(oldTree)
				.map(transformNodesRecursively(this::addDeclaredFields))
				.map(transformNodesRecursively(this::addJointableEntityCollections))
				.map(transformNodesRecursively(this::addEntityCollections))
				.map(transformNodesRecursively(this::addEntityReferences))
				.map(transformNodesRecursively(this::addIdFields))
				.map(transformNodesRecursively(this::addScalarValues))
				.map(transformNodesRecursively(this::applyDefaultIdFieldNames))
				.map(transformNodesRecursively(this::applyDefaultForeignKeyColumnNames))
				.map(transformNodesRecursively(this::applyDefaultJoinConditions))
				.map(transformNodesRecursively(this::applyDefaultScalarExpressions))
				.map(transformNodesRecursively(this::makeSingleIdFieldsAutoIncrement))
				.orElse(null);
		} while(!oldTree.equals(newTree));

		return (RootNode) newTree;
	}

	record FieldValues(Map<String, Object> values, Map<String, Object> idValues, String autoGenIdField) {}

	private static FieldValues collectFields(RootNode tree, Object entity) {
		Map<String, Object> values = new LinkedHashMap<>();
		Map<String, Object> idValues = new LinkedHashMap<>();
		String autoGenIdField = null;

		for (QueryNode children : tree.children()) {
			if (children instanceof FieldNode fieldNode && fieldNode.field() != null) {
				String fieldName = fieldNode.field().getName();
				String columnName = fieldNode.columnName();
				Object value = getFieldValue(entity, fieldNode.field());

				if (fieldNode instanceof PrimaryKey pk) {
					if (pk.isAutoGenerated()) {
						if (value != null) {
							throw new IllegalStateException("Auto-generated ID field '" + fieldName + "' should not have a value");
						}
						autoGenIdField = fieldName;
					} else {
						if (value == null) {
							throw new IllegalStateException("ID field '" + fieldName + "' must have a value");
						}
					}
					idValues.put(columnName, value);
				} else if (fieldNode instanceof EntityReference entityRef) {
					// For entity references, we want to collect the ID value of the referenced entity
					if (value != null) {
						FieldModel referencedIdField = entityRef.children().stream()
							.filter(child -> child instanceof PrimaryKey)
							.map(child -> ((PrimaryKey) child).field())
							.findFirst()
							.orElseThrow(() -> new IllegalStateException("Referenced entity in field '" + fieldName + "' does not have an ID field"));
						Object referencedIdValue = getFieldValue(value, referencedIdField);
						if (referencedIdValue == null) {
							throw new IllegalStateException("Referenced entity in field '" + fieldName + "' has null ID value");
						}
						values.put(columnName, referencedIdValue);
					} else {
						values.put(columnName, null);
					}
				} else if (fieldNode instanceof ScalarValue) {
					values.put(columnName, value);
				}
			}
		}
		return new FieldValues(values, idValues, autoGenIdField);
	}

	@Test
	public void testSql() {
		DefaultSqlQuery sqlQuery = new DefaultSqlQuery(DbContext.getDefault());
		toSql(buildQueryTreeForType(ArticleDetail.class), sqlQuery);
		System.out.println("Generated SQL: " + sqlQuery.toStatement().getSql());
	}

	private void queryRows(Connection conn, Class<?> entityType, Consumer<Map<String, Object>> rowConsumer) {
		RootNode tree = buildQueryTreeForType(entityType);
		DefaultSqlQuery sqlQuery = new DefaultSqlQuery(DbContext.getDefault());
		toSql(tree, sqlQuery);
		DB.queryRowsStreaming(conn, sqlQuery.toStatement(), rowConsumer);
	}

	private <PK> PK insert(Connection conn, Object entity) {
		RootNode tree = buildQueryTreeForType(entity.getClass());
		FieldValues fieldValues = collectFields(tree, entity);
		// Assert.assertEquals("Jane Austen", fieldValues.values().get("name"));
		Assert.assertNull(fieldValues.idValues().get("id"));
		PK generatedId = DB.insert(conn, tree.tableInfo().schemaName(), tree.tableInfo().tableName(), fieldValues.values());
		if (fieldValues.autoGenIdField() != null) {
			setFieldValue(entity, tree.children().stream()
				.filter(child -> child instanceof PrimaryKey pk && pk.field().getName().equals(fieldValues.autoGenIdField()))
				.map(child -> ((PrimaryKey) child).field())
				.findFirst()
				.orElseThrow(() -> new IllegalStateException("Auto-generated ID field '" + fieldValues.autoGenIdField() + "' not found in query tree")), 
				generatedId
			);
		}
		return generatedId;
	}

	@Test
	public void testGenerateInserts() {
		RootNode tree = buildQueryTreeForType(Person.class);
		Assert.assertEquals(2, tree.children().size());
		tree.children().forEach(child -> {
			Assert.assertTrue(child instanceof FieldNode);
			FieldNode fieldNode = (FieldNode) child;
			Assert.assertTrue(fieldNode.field().getName().equals("id") ? fieldNode instanceof PrimaryKey : true);
			Assert.assertTrue(fieldNode.field().getName().equals("name") ? !(fieldNode instanceof PrimaryKey) : true);
		});

		DataSource db = initDatabase();
		
		DB.withConnection(db, conn -> {
			Person albert = new Person();
			albert.name = "Albert Einstein";
			insert(conn, albert);

			ArticleDetail article = new ArticleDetail();
			article.title = "Relativity";
			article.author = albert;
			insert(conn, article);

			queryRows(conn, ArticleDetail.class, row -> {
				buildQueryTreeForType(ArticleDetail.class).children().forEach(child -> {
					if (child instanceof FieldNode fieldNode) {
						System.out.println("Selected column: " + fieldNode.columnName() + " (field: " + fieldNode.field().getName() + ")");
					}
				});
				System.out.println("Queried row: " + row);
				Assert.assertEquals("Relativity", row.get("article.title"));
				Assert.assertEquals("Albert Einstein", row.get("author.name"));
			});
		});
	}

	@Test
	public void test() {
		RootNode root = buildQueryTreeForType(ArticleDetail.class);
		Assert.assertEquals("article", root.alias());
		Assert.assertEquals(5, root.children().size());
		Assert.assertEquals("article_category", new ReflectionTypeModel(ArticleDetail.class).getDeclaredFields().stream()
			.filter(f -> f.getName().equals("categories")).findFirst()
			.map(f -> f.getAnnotationAttributeValue(Link.class, "linktable", String.class)).orElse(""));
		
		findNodes(root, n -> n instanceof EntityReference && ((EntityReference) n).field().getName().equals("author"))
			.map(n -> (EntityReference) n)
			.findFirst()
			.ifPresentOrElse(authorNode -> {
				Assert.assertEquals("author", authorNode.alias());
				Assert.assertEquals(2, authorNode.children().size());
			}, () -> {
				throw new AssertionError("Author node not found");
			});

		findNodes(root, n -> n instanceof EntityCollection && ((EntityCollection) n).field().getName().equals("comments"))
			.map(n -> (EntityCollection) n)
			.findFirst()
			.ifPresentOrElse(commentsNode -> {
				Assert.assertEquals("comments", commentsNode.alias());
				Assert.assertEquals(2, commentsNode.children().size());
			}, () -> {
				throw new AssertionError("Comments node not found");
			});

		findNodes(root, n -> n instanceof JoinTableEntityCollection jten && jten.field().getName().equals("categories"))
			.map(JoinTableEntityCollection.class::cast)
			.findFirst()
			.ifPresentOrElse(categoriesNode -> {
				Assert.assertEquals("categories", categoriesNode.alias());
				Assert.assertEquals(2, categoriesNode.children().size());
				JoinTableInfo joinTableInfo = categoriesNode.join().joinTableInfo();
				Assert.assertEquals("categories.article_category", joinTableInfo.joinTableAlias());
				// After buildQueryTreeForType applies all transforms, FK column names should be set
				Assert.assertEquals("article_id", categoriesNode.join().parentKey().fkColumnName());
				Assert.assertEquals("category_id", categoriesNode.join().childKey().fkColumnName());
				Assert.assertEquals("article_category", joinTableInfo.tableInfo().tableName());

				categoriesNode.children().forEach(child -> {
					Assert.assertTrue(child instanceof ScalarValue);
					ScalarValue scalarChild = (ScalarValue) child;
					Assert.assertTrue(scalarChild.field().getName().equals("id") || scalarChild.field().getName().equals("name"));
				});
			}, () -> {
				throw new AssertionError("Categories node not found");
			});

		// The expected structure of the query tree is:
		// RootNode (Article)
		//   - ScalarValue (id)
		//   - ScalarValue (title)
		//   - EntityReference (author)
		//       - ScalarValue (id)
		//       - ScalarValue (name)
		//   - EntityCollection (comments)
		//       - ScalarValue (id)
		//       - ScalarValue (content)
		// Example of building a query tree with this structure:
		// RootNode (Article)
		//   - ScalarValue (id)
		//   - ScalarValue (title)
		//   - EntityReference (author)
		//       - ScalarValue (id)
		//       - ScalarValue (name)
		//   - EntityCollection (comments)
		//       - ScalarValue (id)
		//       - ScalarValue (content)
	}



	@Test
	public void testAlternativeStructure() {
		// This test just checks that we can build a query tree with an alternative structure (using a different class for the nodes).
		// The actual correctness of the query tree is not checked here, but it should be covered by other tests.
		// PojoQuery.build(TestBasics.ArticleDetail.class, AlternativeQueryTreeNode.class);
	}

	public static Stream<QueryNode> findNodes(QueryNode node, Predicate<QueryNode> condition) {
		Stream<QueryNode> current = Stream.of(node);
		if (node instanceof TableNode tableNode && tableNode.children() != null) {
			current = Stream.concat(current, tableNode.children().stream().flatMap(child -> findNodes(child, condition)));
		}
		return current.filter(condition);
	}

	private TableInfo determinTableInfo(TypeModel type) {
		List<TableMapping> mapping = PojoMetadata.determineTableMapping(type);
		if (mapping.isEmpty()) {
			throw new IllegalArgumentException("Type " + type.getQualifiedName() + " is not an entity");
		}
		return new TableInfo(mapping.get(0).schemaName, mapping.get(0).tableName);
	}

	public Function<QueryNode, QueryNode> transformNodesRecursively(Function<QueryNode, QueryNode> transform) {
		return node -> {
			QueryNode transformed = transform.apply(node);
			if (transformed instanceof TableNode tableNode && tableNode.children() != null) {
				List<QueryNode> newChildren = tableNode.children().stream()
					.map(transformNodesRecursively(transform))
					.toList();
				return tableNode.withChildren(newChildren);
			} else {
				return transformed;
			}
		};
	}

	private DataSource initDatabase() {
		DbContext.setDefault(DbContext.forDialect(Dialect.HSQLDB));

        JDBCDataSource ds = new JDBCDataSource();
        ds.setUrl("jdbc:hsqldb:mem:testdb");
        ds.setUser("SA");
        ds.setPassword("");
        DbContext.setDefault(DbContext.forDialect(DbContext.Dialect.HSQLDB));

		RootNode articleNode = buildQueryTreeForType(ArticleDetail.class);

		List<String> ddlStatements = generateCreateSchemaDDL(DbContext.getDefault(), articleNode);
		
		// Create an hsql in-memory database and execute the DDL statements to verify they are correct
		try (Connection conn = ds.getConnection()) {
			try (Statement stmt = conn.createStatement()) {
				for (String ddl : ddlStatements) {
					System.out.println("Executing DDL: " + ddl);
					stmt.execute(ddl);
				}
			}
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
		return ds;
	}

	private static Object getFieldValue(Object entity, FieldModel fieldModel) {
		try {
			Field field = ((ReflectionFieldModel)fieldModel).getReflectionField();
			field.setAccessible(true);
			return field.get(entity);
		} catch (IllegalAccessException e) {
			return null;
		}
	}

	private static void setFieldValue(Object entity, FieldModel fieldModel, Object value) {
		try {
			Field field = ((ReflectionFieldModel)fieldModel).getReflectionField();
			field.setAccessible(true);
			field.set(entity, value);
		} catch (IllegalAccessException e) {
			throw new RuntimeException(e);
		}
	}
}
