package org.pojoquery.typedquery;

import java.util.Collection;

import org.pojoquery.SqlExpression;

/**
 * Represents a type-safe reference to an entity field for use in queries.
 *
 * <p>QueryField instances are generated by the annotation processor and provide
 * compile-time safety for field references in queries. Each field knows its
 * column name, alias, and Java type.
 *
 * <p>Fields can create conditions directly using jOOQ-style methods:
 * <pre>{@code
 * Condition myth nameFilter = lastName.eq("Smith").or(lastName.eq("Johnson"));
 * new EmployeeQuery().where(nameFilter).list(connection);
 * }</pre>
 *
 * @param <E> the entity type this field belongs to
 * @param <T> the Java type of the field
 */
public class QueryField<E, T> {

    private final String alias;
    private final String columnName;
    private final String fieldName;
    private final Class<T> fieldType;

    /**
     * Creates a new QueryField.
     *
     * @param alias      the table alias (e.g., "employee")
     * @param columnName the database column name
     * @param fieldName  the Java field name
     * @param fieldType  the Java type of the field
     */
    public QueryField(String alias, String columnName, String fieldName, Class<T> fieldType) {
        this.alias = alias;
        this.columnName = columnName;
        this.fieldName = fieldName;
        this.fieldType = fieldType;
    }

    /**
     * Returns the table alias for this field.
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Returns the database column name.
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * Returns the Java field name.
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Returns the Java type of this field.
     */
    public Class<T> getFieldType() {
        return fieldType;
    }

    /**
     * Returns the fully qualified column reference (alias.column).
     */
    public String getQualifiedColumn() {
        return "{" + alias + "}." + columnName;
    }

    @Override
    public String toString() {
        return getQualifiedColumn();
    }

    // === Condition-building methods (jOOQ-style) ===

    /**
     * Creates an equality condition: field = value
     */
    public Condition<E> eq(T value) {
        return new Condition<>(getQualifiedColumn() + " = ?", value);
    }

    /**
     * Creates a not-equal condition: field != value
     */
    public Condition<E> ne(T value) {
        return new Condition<>(getQualifiedColumn() + " != ?", value);
    }

    /**
     * Creates an IS NULL condition.
     */
    public Condition<E> isNull() {
        return new Condition<>(getQualifiedColumn() + " IS NULL");
    }

    /**
     * Creates an IS NOT NULL condition.
     */
    public Condition<E> isNotNull() {
        return new Condition<>(getQualifiedColumn() + " IS NOT NULL");
    }

    /**
     * Creates a LIKE condition: field LIKE pattern
     */
    public Condition<E> like(String pattern) {
        return new Condition<>(getQualifiedColumn() + " LIKE ?", pattern);
    }

    /**
     * Creates a NOT LIKE condition.
     */
    public Condition<E> notLike(String pattern) {
        return new Condition<>(getQualifiedColumn() + " NOT LIKE ?", pattern);
    }

    /**
     * Creates an IN condition: field IN (values)
     */
    public Condition<E> in(Collection<? extends T> values) {
        if (values == null || values.isEmpty()) {
            return Condition.alwaysFalse();
        }
        StringBuilder sb = new StringBuilder(getQualifiedColumn());
        sb.append(" IN (");
        boolean first = true;
        for (T value : values) {
            if (!first) sb.append(", ");
            sb.append("?");
            first = false;
        }
        sb.append(")");
        return new Condition<>(sb.toString(), values.toArray());
    }

    /**
     * Creates an IN condition with varargs.
     */
    @SafeVarargs
    public final Condition<E> in(T... values) {
        if (values == null || values.length == 0) {
            return Condition.alwaysFalse();
        }
        StringBuilder sb = new StringBuilder(getQualifiedColumn());
        sb.append(" IN (");
        for (int i = 0; i < values.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append("?");
        }
        sb.append(")");
        return new Condition<>(sb.toString(), values);
    }

    /**
     * Creates a NOT IN condition.
     */
    public Condition<E> notIn(Collection<? extends T> values) {
        if (values == null || values.isEmpty()) {
            return Condition.alwaysTrue();
        }
        StringBuilder sb = new StringBuilder(getQualifiedColumn());
        sb.append(" NOT IN (");
        boolean first = true;
        for (T value : values) {
            if (!first) sb.append(", ");
            sb.append("?");
            first = false;
        }
        sb.append(")");
        return new Condition<>(sb.toString(), values.toArray());
    }
}
