package org.pojoquery.typedquery;

/**
 * Represents a type-safe reference to an entity field for use in queries.
 *
 * <p>QueryField instances are generated by the annotation processor and provide
 * compile-time safety for field references in queries. Each field knows its
 * column name, alias, and Java type.
 *
 * @param <E> the entity type this field belongs to
 * @param <T> the Java type of the field
 */
public class QueryField<E, T> {

    private final String alias;
    private final String columnName;
    private final String fieldName;
    private final Class<T> fieldType;

    /**
     * Creates a new QueryField.
     *
     * @param alias      the table alias (e.g., "employee")
     * @param columnName the database column name
     * @param fieldName  the Java field name
     * @param fieldType  the Java type of the field
     */
    public QueryField(String alias, String columnName, String fieldName, Class<T> fieldType) {
        this.alias = alias;
        this.columnName = columnName;
        this.fieldName = fieldName;
        this.fieldType = fieldType;
    }

    /**
     * Returns the table alias for this field.
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Returns the database column name.
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * Returns the Java field name.
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Returns the Java type of this field.
     */
    public Class<T> getFieldType() {
        return fieldType;
    }

    /**
     * Returns the fully qualified column reference (alias.column).
     */
    public String getQualifiedColumn() {
        return "{" + alias + "}." + columnName;
    }

    @Override
    public String toString() {
        return getQualifiedColumn();
    }
}
