package org.pojoquery.pipeline;

import java.util.List;
import java.util.Map;
import java.util.Objects;

import org.pojoquery.JdbcValueMapper;
import org.pojoquery.SqlExpression;
import org.pojoquery.annotations.Recursive;
import org.pojoquery.typemodel.FieldModel;
import org.pojoquery.typemodel.TypeModel;

/**
 * Abstract Query Tree (AQT) - an intermediate representation of POJO structures
 * as query trees.
 * 
 * <p>
 * The AQT transforms Java class hierarchies into a tree structure that can be
 * converted to SQL.
 * Each node represents either a table/entity or a field/column mapping. The
 * tree is immutable;
 * all modification methods return new instances.
 * 
 * <h2>Node Type Hierarchy</h2>
 * 
 * <p>
 * Java properties are transformed into one of these node types:
 * <ul>
 * <li>{@link ScalarValue} - primitive value or string mapped to a column or SQL
 * expression</li>
 * <li>{@link EntityReference} - many-to-one or one-to-one reference to another
 * entity (LEFT JOIN)</li>
 * <li>{@link EntityCollection} - one-to-many collection of entities (LEFT
 * JOIN)</li>
 * <li>{@link ValueCollection} - collection of scalar values from a one-to-many
 * join</li>
 * <li>{@link JoinTableEntityCollection} - many-to-many collection via junction
 * table</li>
 * <li>{@link JoinTableValueCollection} - scalar collection via junction
 * table</li>
 * <li>{@link EmbeddedEntity} - embedded object sharing the parent's table</li>
 * </ul>
 * 
 * <h2>Inheritance Support</h2>
 * 
 * <p>
 * Two inheritance strategies are supported:
 * <ul>
 * <li><b>Table-Per-Subclass (TPS)</b>: {@link TPSSuperClassNode},
 * {@link TPSSubClassNode} -
 * each class has its own table, joined by primary key</li>
 * <li><b>Single Table Inheritance (STI)</b>: {@link STISuperClassNode},
 * {@link STISubClassNode} -
 * all classes share one table with a discriminator column</li>
 * </ul>
 * 
 * @see org.pojoquery.pipeline.Transforms
 */
public class AbstractQueryTree {

	/**
	 * Base interface for all nodes in the query tree.
	 * 
	 * <p>
	 * The sealed hierarchy ensures exhaustive pattern matching in switch
	 * expressions.
	 */
	public sealed interface QueryNode
			permits TableNode, EmptyTableNode, EmptyFieldNode, FieldNode, CustomQueryNode, CustomJoin {
	}

	/**
	 * Extension point for custom query behavior not covered by standard node types.
	 * 
	 * <p>
	 * Implementations can inject custom SQL into the query and process result rows.
	 */
	public non-sealed interface CustomQueryNode extends QueryNode {
		/** Adds custom SQL expressions, joins, or conditions to the query. */
		void applyToSqlQuery(TableNode parentNode, AQTTransformer.PlainQueryBuilder sqlQuery);

		/**
		 * Extracts custom values from the result row and applies them to the entity.
		 */
		void applyRowResultToEntity(TableNode parentNode, Object targetEntity, Map<String, Object> fullRow);
	}

	public record CustomJoin(String alias, String parentAlias, TableInfo joinedTable, SqlQuery.JoinType joinType,
			SqlExpression joinCondition) implements QueryNode {
	}

	/**
	 * A field node that maps to scalar (non-entity) values.
	 * 
	 * <p>
	 * Scalar nodes represent columns containing primitive types, strings, enums,
	 * or other non-entity values that don't require joins to load.
	 */
	public sealed interface ScalarNode
			extends FieldNode
			permits PrimaryKeyField, ScalarValue, AggregateScalarValue {
	}

	/**
	 * Marker interface for primary key fields.
	 * 
	 * <p>
	 * Primary keys are used for entity identity, join conditions, and determining
	 * whether to INSERT or UPDATE during persistence.
	 */
	public non-sealed interface PrimaryKeyField extends ScalarNode, ColumnFieldNode {
		/**
		 * Returns true if the database auto-generates this key
		 * (IDENTITY/SERIAL/AUTO_INCREMENT).
		 */
		Boolean isAutoGenerated();
	}

	/**
	 * Node representing a superclass in an inheritance hierarchy.
	 * 
	 * <p>
	 * Superclass nodes contain fields inherited by subclasses. The join strategy
	 * depends on the concrete implementation (TPS or STI).
	 */
	public sealed interface SuperClassNode extends TableNode permits STISuperClassNode, TPSSuperClassNode {
		String alias();
	}

	/**
	 * Node representing a subclass in an inheritance hierarchy.
	 * 
	 * <p>
	 * Subclass nodes contain additional fields specific to the subclass.
	 */
	public sealed interface SubClassNode extends TableNode permits STISubClassNode, TPSSubClassNode {
		/** Alias of the parent class node in the tree. */
		String parentAlias();
	}

	/**
	 * A node that represents a database table and contains child nodes.
	 * 
	 * <p>
	 * Table nodes form the backbone of the query tree. Each table node generates
	 * a table reference in the FROM or JOIN clause, with its children determining
	 * the selected columns and nested joins.
	 */
	public sealed interface TableNode
			extends QueryNode
			permits Embedding, RootNode, EntityNode, EntityCollection, JoinTableEntityCollection, SubQueryCollection,
			RecursiveCollection,
			SuperClassNode, SubClassNode {
		/** SQL alias used to reference this table in the query. */
		String alias();

		/** The Java type this table maps to. */
		TypeModel type();

		/** source table or subquery (name, schema). */
		TableInfo tableInfo();

		/** Child nodes (fields and nested entities). */
		List<QueryNode> children();

		/** Returns a copy with the given children. */
		TableNode withChildren(List<? extends QueryNode> newChildren);
	}

	/**
	 * A table node that shares columns with another table (no separate JOIN).
	 * 
	 * <p>
	 * Used for embedded objects and single-table inheritance where multiple
	 * Java types map to columns in the same database table.
	 */
	public sealed interface Embedding extends TableNode
			permits EmbeddedEntity, STINode {
		/** Alias of the table that contains the actual columns. */
		String sourceAlias();
	}

	/**
	 * Table-Per-Subclass subclass node - joins to parent table via primary key.
	 * 
	 * <p>
	 * In TPS inheritance, each subclass has its own table containing only its
	 * declared fields. The subclass table joins to the parent table on the shared
	 * primary key.
	 */
	public record TPSSubClassNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			ForeignKeyInfo join, String parentAlias)
			implements Join, SubClassNode {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new TPSSubClassNode(alias, type, tableInfo, List.copyOf(newChildren), join, parentAlias);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new TPSSubClassNode(alias, type, tableInfo, children, newJoin, parentAlias);
		}
	}

	/**
	 * Table-Per-Subclass superclass node - contains inherited fields in separate
	 * table.
	 * 
	 * <p>
	 * When querying a subclass, this node represents the parent table that must
	 * be joined to retrieve inherited fields.
	 */
	public record TPSSuperClassNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			ForeignKeyInfo join, String parentAlias)
			implements Join, SuperClassNode {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new TPSSuperClassNode(alias, type, tableInfo, List.copyOf(newChildren), join, parentAlias);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new TPSSuperClassNode(alias, type, tableInfo, children, newJoin, parentAlias);
		}
	}

	/**
	 * Single Table Inheritance superclass node - shares table with all subclasses.
	 * 
	 * <p>
	 * In STI, the discriminator column determines which Java type to instantiate.
	 * This node represents the superclass portion of the shared table.
	 */
	public record STISuperClassNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			String sourceAlias,
			String discriminatorColumn, Object discriminatorValue, String parentAlias)
			implements STINode, SuperClassNode {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new STISuperClassNode(alias, type, tableInfo, List.copyOf(newChildren),
					sourceAlias, discriminatorColumn, discriminatorValue, parentAlias);
		}
	}

	/**
	 * Single Table Inheritance subclass node - shares table with parent (no join).
	 * 
	 * <p>
	 * STI subclasses read from the same table as their parent. The discriminator
	 * value identifies rows belonging to this specific subclass. Columns for fields
	 * not present in this subclass may contain NULL.
	 * 
	 * @param discriminatorColumn the column containing the type discriminator
	 * @param discriminatorValue  the value that identifies this subclass
	 */
	public record STISubClassNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			String sourceAlias, TypeModel superClass,
			String discriminatorColumn, Object discriminatorValue, String parentAlias)
			implements STINode, SubClassNode {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new STISubClassNode(alias, type, tableInfo, List.copyOf(newChildren),
					sourceAlias, superClass, discriminatorColumn, discriminatorValue, parentAlias);
		}

		public QueryNode withDiscriminatorColumn(String discriminatorColumn) {
			return new STISubClassNode(alias, type, tableInfo, children, sourceAlias, superClass, discriminatorColumn,
					discriminatorValue, parentAlias);
		}

		public QueryNode withDiscriminatorValue(Object discriminatorValue) {
			return new STISubClassNode(alias, type, tableInfo, children, sourceAlias, superClass, discriminatorColumn,
					discriminatorValue, parentAlias);
		}
	}

	/**
	 * Single Table Inheritance node - a class in an STI hierarchy.
	 * 
	 * <p>
	 * STI nodes share a table with their parent/children. The discriminator column
	 * contains a value that identifies which concrete type each row represents.
	 * No JOIN is generated for STI relationships.
	 */
	public sealed interface STINode extends Embedding
			permits STISuperClassNode, STISubClassNode {
		/** The discriminator value that identifies this type. */
		Object discriminatorValue();

		/** The column name containing the type discriminator. */
		String discriminatorColumn();
	}

	/**
	 * A node that maps to a Java field or property.
	 * 
	 * <p>
	 * Field nodes represent the leaf level of property mappings, though
	 * entity fields may themselves contain nested children.
	 */
	public non-sealed interface FieldNode extends QueryNode {
		/** The Java field this node maps to. */
		FieldModel field();
	}

	/**
	 * A field that references an entity type, combining field and table
	 * characteristics.
	 * 
	 * <p>
	 * Entity nodes are both fields (they map to a Java property) and tables
	 * (they generate JOINs and have nested children). Examples include
	 * {@link EntityReference} and {@link EmbeddedEntity}.
	 */
	public non-sealed interface EntityNode extends FieldNode, TableNode {
	}

	/**
	 * A node with an associated database column name.
	 */
	public interface Column {
		/** The database column name. */
		String columnName();

		/** Returns a copy with the given column name. */
		QueryNode withColumnName(String columnName);
	}

	/**
	 * A field that maps to a column in the current or parent table.
	 * 
	 * <p>
	 * This is distinguished from collection fields where the foreign key
	 * resides in the child table rather than the current table.
	 */
	public interface ColumnFieldNode extends MappedFieldNode, Column {
	}

	/**
	 * A field node with JDBC value conversion support.
	 * 
	 * <p>
	 * The value mapper handles conversion between Java types and JDBC types,
	 * including custom conversions for enums, JSON, and other complex types.
	 */
	public interface MappedFieldNode extends FieldNode {
		/** The converter for JDBC value mapping, or null for default conversion. */
		JdbcValueMapper valueMapper();

		/** Returns a copy with the given value mapper. */
		public FieldNode withValueMapper(JdbcValueMapper valueMapper);
	}

	/**
	 * Placeholder for a field that has not yet been fully resolved.
	 * 
	 * <p>
	 * Used during tree construction before the field's mapping type is determined.
	 */
	public non-sealed interface EmptyFieldNode extends QueryNode {
		FieldModel field();
	}

	/**
	 * Placeholder for a table that has not yet been populated with children.
	 * 
	 * <p>
	 * Used during tree construction as an intermediate state.
	 */
	public record EmptyTableNode(String alias, TypeModel type, TableInfo tableInfo) implements QueryNode {
	}

	/**
	 * A generic mapped field with value conversion support.
	 */
	public record MappedField(String alias, TypeModel type, FieldModel field, JdbcValueMapper valueMapper)
			implements MappedFieldNode {
		public FieldNode withValueMapper(JdbcValueMapper valueMapper) {
			return new MappedField(alias, type, field, valueMapper);
		}

		public QueryNode withColumnName(String columnName) {
			return new MappedField(alias, type, field, valueMapper);
		}
	}

	/**
	 * The root of a query tree, representing the main FROM table.
	 * 
	 * <p>
	 * The root node also carries query-level clauses like GROUP BY and ORDER BY.
	 * 
	 * @param alias     the table alias used in SQL
	 * @param type      the root entity type being queried
	 * @param tableInfo database table metadata
	 * @param children  field and entity nodes to select
	 * @param groupBy   GROUP BY expressions (may contain {alias} placeholders)
	 * @param orderBy   ORDER BY expressions (may contain {alias} placeholders)
	 */
	public record RootNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			List<String> groupBy, List<String> orderBy)
			implements TableNode {
		public RootNode withChildren(List<? extends QueryNode> newChildren) {
			return new RootNode(alias, type, tableInfo, List.copyOf(newChildren), groupBy, orderBy);
		}

		public RootNode withGroupByClauses(List<String> groupBy) {
			return new RootNode(alias, type, tableInfo, children, List.copyOf(groupBy), orderBy);
		}

		public RootNode withOrderByClauses(List<String> orderBy) {
			return new RootNode(alias, type, tableInfo, children, groupBy, List.copyOf(orderBy));
		}

		public RootNode withTableInfo(TableInfo tableInfo) {
			return new RootNode(alias, type, tableInfo, children, groupBy, orderBy);
		}

		public RootNode withAlias(String alias) {
			return new RootNode(alias, type, tableInfo, children, groupBy, orderBy);
		}

		public static RootNode createEmptyRootNode(TypeModel rootType) {
			return new RootNode(null, rootType, null, null, null, null);
		}

	}

	/**
	 * An embedded entity whose fields are stored in the parent's table.
	 * 
	 * <p>
	 * Embedded entities don't generate JOINs. Their columns are prefixed to avoid
	 * name collisions with the parent's columns.
	 * 
	 * @param sourceAlias alias of the table containing the columns
	 * @param fieldPrefix prefix applied to column names (e.g., "address_")
	 */
	public record EmbeddedEntity(String alias, TypeModel type, String sourceAlias, TableInfo tableInfo,
			List<QueryNode> children, FieldModel field, String fieldPrefix) implements Embedding, EntityNode {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EmbeddedEntity(alias, type, sourceAlias, tableInfo, List.copyOf(newChildren), field,
					fieldPrefix);
		}

		public static QueryNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias, TypeModel embeddedType,
				String sourceAlias, TableInfo tableInfo, String fieldPrefix) {
			return new EmbeddedEntity(alias, embeddedType, sourceAlias, tableInfo, null, emptyFieldNode.field(),
					fieldPrefix);
		}
	}

	/**
	 * A scalar (non-entity) field mapped to a database column or SQL expression.
	 * 
	 * <p>
	 * This is the most common field type, representing primitives, strings,
	 * enums, dates, and other simple values.
	 * 
	 * @param columnName the database column name (may differ from field name)
	 * @param expression custom SQL expression for computed columns (@Select
	 *                   annotation)
	 */
	public record ScalarValue(FieldModel field, String columnName, SqlExpression expression,
			JdbcValueMapper valueMapper) implements ScalarNode, ColumnFieldNode {

		public ScalarValue withExpression(SqlExpression sql) {
			return new ScalarValue(field, columnName, sql, valueMapper);
		}

		public ScalarValue withValueMapper(JdbcValueMapper valueMapper) {
			return new ScalarValue(field, columnName, expression, valueMapper);
		}

		public ScalarValue withColumnName(String columnName) {
			return new ScalarValue(field, columnName, expression, valueMapper);
		}

		public static QueryNode ofEmptyFieldNode(EmptyFieldNode emptyFieldNode) {
			return new ScalarValue(emptyFieldNode.field(), null, null, null);
		}

	}

	/**
	 * A scalar field with an aggregate SQL expression (COUNT, SUM, MAX, etc.).
	 * 
	 * <p>
	 * Aggregate fields trigger automatic GROUP BY generation for non-aggregate
	 * scalar fields in the same query. The expression must contain an aggregate
	 * function.
	 * 
	 * @param columnName the output column name (usually derived from field name)
	 * @param expression the aggregate SQL expression (e.g., "COUNT({alias.id})")
	 * @see org.pojoquery.annotations.Aggregate
	 */
	public record AggregateScalarValue(FieldModel field, String columnName, SqlExpression expression,
			JdbcValueMapper valueMapper) implements ScalarNode, ColumnFieldNode {

		public AggregateScalarValue withExpression(SqlExpression sql) {
			return new AggregateScalarValue(field, columnName, sql, valueMapper);
		}

		public AggregateScalarValue withValueMapper(JdbcValueMapper valueMapper) {
			return new AggregateScalarValue(field, columnName, expression, valueMapper);
		}

		public AggregateScalarValue withColumnName(String columnName) {
			return new AggregateScalarValue(field, columnName, expression, valueMapper);
		}

		public static AggregateScalarValue fromScalarValue(ScalarValue scalar) {
			return new AggregateScalarValue(scalar.field(), scalar.columnName(), scalar.expression(),
					scalar.valueMapper());
		}
	}

	/**
	 * Primary key field implementation.
	 * 
	 * @param isAutoGenerated true if the database generates values
	 *                        (IDENTITY/SERIAL/AUTO_INCREMENT)
	 */
	public record PrimaryKey(FieldModel field, String columnName, SqlExpression expression, Boolean isAutoGenerated,
			JdbcValueMapper valueMapper)
			implements PrimaryKeyField {

		public static PrimaryKey fromField(FieldModel field) {
			return new PrimaryKey(field, null, null, null, null);
		}

		public PrimaryKey withExpression(SqlExpression sql) {
			return new PrimaryKey(field, columnName, sql, isAutoGenerated, valueMapper);
		}

		public PrimaryKey setAutoGenerated(boolean b) {
			return new PrimaryKey(field, columnName, expression, b, valueMapper);
		}

		public PrimaryKey withValueMapper(JdbcValueMapper valueMapper) {
			return new PrimaryKey(field, columnName, expression, isAutoGenerated, valueMapper);
		}

		public PrimaryKey withColumnName(String columnName) {
			return new PrimaryKey(field, columnName, expression, isAutoGenerated, valueMapper);
		}
	}

	/**
	 * A node that generates a SQL JOIN clause.
	 * 
	 * <p>
	 * Join nodes connect tables via foreign key relationships. The join
	 * information specifies which columns form the relationship.
	 */
	public sealed interface Join permits JoinOne, JoinMany, TPSSuperClassNode, TPSSubClassNode {
		/** Alias of the parent (source) table in the join. */
		String parentAlias();

		/** Foreign key relationship details. */
		ForeignKeyInfo join();

		/** Returns a copy with the given join info. */
		QueryNode withJoin(ForeignKeyInfo newJoin);
	}

	/**
	 * A one-to-many join where the foreign key is in the child table.
	 */
	public sealed interface JoinMany extends FieldNode, Join {
	}

	/**
	 * A many-to-one or one-to-one join where the foreign key is in the parent
	 * table.
	 */
	public sealed interface JoinOne extends ColumnFieldNode, Join {
	}

	/**
	 * A collection of scalar values from a one-to-many relationship.
	 * 
	 * <p>
	 * Unlike {@link EntityCollection}, this collects primitive/string values
	 * rather than entities. For example, a list of tags stored in a separate table.
	 * 
	 * @param componentType the type of elements in the collection (e.g., String)
	 * @param fetchColumn   the column containing the values to collect
	 */
	public record ValueCollection(FieldModel field, String alias, TypeModel componentType, TableInfo joinTable,
			String fetchColumn, String parentAlias, ForeignKeyInfo join, SqlExpression expression,
			JdbcValueMapper valueMapper)
			implements JoinMany {

		public static ValueCollection fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
				TypeModel componentType, TableInfo joinTable, String fetchColumn, String parentAlias,
				ForeignKeyInfo join) {
			return new ValueCollection(emptyFieldNode.field(), alias, componentType, joinTable, fetchColumn,
					parentAlias, join, null, null);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new ValueCollection(field, alias, componentType, joinTable, fetchColumn, parentAlias, newJoin,
					expression, valueMapper);
		}

		public QueryNode withExpression(SqlExpression sql) {
			return new ValueCollection(field, alias, componentType, joinTable, fetchColumn, parentAlias, join, sql,
					valueMapper);
		}

		public ValueCollection withValueMapper(JdbcValueMapper valueMapper) {
			return new ValueCollection(field, alias, componentType, joinTable, fetchColumn, parentAlias, join,
					expression, valueMapper);
		}
	}

	/**
	 * Metadata about a junction (join) table used in many-to-many relationships.
	 * 
	 * @param tableInfo      the junction table's database metadata
	 * @param joinTableAlias SQL alias for the junction table
	 */
	public record JoinTableInfo(TableInfo tableInfo, String joinTableAlias) {
	}

	/**
	 * Describes a foreign key relationship between two tables.
	 * 
	 * <p>
	 * This record captures all information needed to generate a JOIN ON clause.
	 * The referring table contains the foreign key column; the target table
	 * contains
	 * the referenced primary key.
	 * 
	 * @param referringTable  table containing the FK column
	 * @param referringAlias  SQL alias for the referring table
	 * @param targetTable     table containing the referenced PK
	 * @param targetAlias     SQL alias for the target table
	 * @param foreignKeyField Java field for the FK (may be null for implicit FKs)
	 * @param fkColumnName    database column name for the FK
	 * @param idField         Java field for the PK
	 * @param idColumnName    database column name for the PK
	 * @param joinCondition   the join condition used in the ON clause of the query
	 *                        JOIN
	 */
	public record ForeignKeyInfo(TableInfo referringTable, String referringAlias, TableInfo targetTable,
			String targetAlias, FieldModel foreignKeyField, String fkColumnName, FieldModel idField,
			String idColumnName, SqlExpression joinCondition) {

		public ForeignKeyInfo {
			Objects.requireNonNull(idField, "idField must not be null");
		}

		public static ForeignKeyInfo fkInParent(TableInfo parentTable, String parentAlias, TableInfo childTable,
				String childAlias, FieldModel foreignKeyField, FieldModel idField) {
			return new ForeignKeyInfo(parentTable, parentAlias, childTable, childAlias, foreignKeyField, null, idField,
					null, null);
		}

		public static ForeignKeyInfo fkInChild(TableInfo parentTable, String parentAlias, TableInfo childTable,
				String childAlias, FieldModel idField) {
			return new ForeignKeyInfo(childTable, childAlias, parentTable, parentAlias, null, null, idField, null,
					null);
		}

		public ForeignKeyInfo withJoinCondition(SqlExpression joinCondition) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField,
					fkColumnName, idField, idColumnName, joinCondition);
		}

		public ForeignKeyInfo withFkColumnName(String fkColumnName) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField,
					fkColumnName, idField, idColumnName, joinCondition);
		}

		public ForeignKeyInfo withIdColumnName(String idColumnName) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField,
					fkColumnName, idField, idColumnName, joinCondition);
		}
	}

	/**
	 * Complete join information for a many-to-many relationship via junction table.
	 * 
	 * <p>
	 * A many-to-many relationship requires two foreign keys: one from the parent
	 * to the junction table, and one from the junction table to the child.
	 * 
	 * @param joinTableInfo the junction table metadata
	 * @param parentKey     FK from parent table to junction table
	 * @param childKey      FK from junction table to child table
	 */
	public record JoinTableJoin(JoinTableInfo joinTableInfo, ForeignKeyInfo parentKey, ForeignKeyInfo childKey) {

		public JoinTableJoin withJoinTableInfo(JoinTableInfo joinTableInfo) {
			return new JoinTableJoin(joinTableInfo, parentKey, childKey);
		}

		public JoinTableJoin withJoinForeignKeyInfo(ForeignKeyInfo parentKey, ForeignKeyInfo childKey) {
			return new JoinTableJoin(joinTableInfo, parentKey, childKey);
		}

	}

	/**
	 * Marker interface for nodes that use a junction table join.
	 */
	public sealed interface HasJoinTableJoin {
		/** The junction table join configuration. */
		JoinTableJoin join();

		/** Returns a copy with the given join table join. */
		QueryNode withJoinTableJoin(JoinTableJoin joinTableJoin);
	}

	/**
	 * A collection of entities joined through a junction (many-to-many) table.
	 * 
	 * <p>
	 * This generates two JOINs: parent → junction table → child entity.
	 * The @Link annotation typically creates this node type.
	 */
	public record JoinTableEntityCollection(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			FieldModel field, JoinTableJoin join, String parentAlias, JdbcValueMapper valueMapper)
			implements TableNode, HasJoinTableJoin, FieldNode {

		public static QueryNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias, TypeModel componentType,
				TableInfo tableInfo, JoinTableJoin join, String parentAlias) {
			return new JoinTableEntityCollection(
					alias,
					componentType,
					tableInfo,
					null,
					emptyFieldNode.field(),
					join,
					parentAlias,
					null);
		}

		@Override
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new JoinTableEntityCollection(alias, type, tableInfo, List.copyOf(newChildren), field, join,
					parentAlias, valueMapper);
		}

		public JoinTableEntityCollection withJoinTableJoin(JoinTableJoin joinTableJoin) {
			return new JoinTableEntityCollection(alias, type, tableInfo, children, field, joinTableJoin, parentAlias,
					valueMapper);
		}

		public JoinTableEntityCollection withValueMapper(JdbcValueMapper valueMapper) {
			return new JoinTableEntityCollection(alias, type, tableInfo, children, field, join, parentAlias,
					valueMapper);
		}

	}

	/**
	 * A collection of scalar values through a junction table (many-to-many of
	 * primitives).
	 * 
	 * <p>
	 * This is a specialized case for collecting non-entity values through a
	 * junction table, less common than {@link JoinTableEntityCollection}.
	 */
	public non-sealed interface JoinTableValueCollection extends HasJoinTableJoin {
		/** Column names to select from the junction table. */
		String[] fieldsToSelect();

		/** Value mapper for converting the selected values. */
		JdbcValueMapper valueMapper();
	}

	/** Default implementation of {@link EmptyFieldNode}. */
	public record EmptyFieldNodeImpl(FieldModel field) implements EmptyFieldNode {
	}

	public record SubQueryJoin(String alias, TableInfo tableInfo, TypeModel type, List<QueryNode> children, FieldModel field, String parentAlias, SqlQuery.JoinType joinType, RootNode subQueryTree, SqlExpression joinCondition) implements EntityNode {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new SubQueryJoin(alias, tableInfo, type, List.copyOf(newChildren), field, parentAlias, joinType, subQueryTree,
					joinCondition);
		}

	}
	/**
	 * A many-to-one or one-to-one entity reference (LEFT JOIN).
	 * 
	 * <p>
	 * The foreign key column resides in the parent table, referencing the
	 * primary key of the related entity.
	 * 
	 * @param columnName the FK column name in the parent table
	 */
	public record EntityReference(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			FieldModel field, String parentAlias, String columnName, ForeignKeyInfo join, JdbcValueMapper valueMapper)
			implements EntityNode, JoinOne {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EntityReference(alias, type, tableInfo, List.copyOf(newChildren), field, parentAlias, columnName,
					join, valueMapper);
		}

		public static EntityReference fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
				TableInfo determinTableInfo, FieldModel field, String parentAlias, ForeignKeyInfo join) {
			return new EntityReference(alias, field.getType(), determinTableInfo, null, field, parentAlias, null, join,
					null);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, newJoin.fkColumnName,
					newJoin, valueMapper);
		}

		public EntityReference withValueMapper(JdbcValueMapper valueMapper) {
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, columnName, join,
					valueMapper);
		}

		public EntityReference withColumnName(String columnName) {
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, columnName, join,
					valueMapper);
		}
	}

	public record SubQueryCollection(String alias, TableInfo tableInfo, TypeModel type, List<QueryNode> children, FieldModel field, String parentAlias, SqlQuery.JoinType joinType, RootNode subQueryTree, SqlExpression joinCondition) implements TableNode {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new SubQueryCollection(alias, tableInfo, type, List.copyOf(newChildren), field, parentAlias, joinType, subQueryTree,
					joinCondition);
		}

	}

	/**
	 * A one-to-many collection populated via a recursive CTE.
	 *
	 * <p>The CTE acts as a junction: it emits {@code (root_id, id, depth)} tuples
	 * that map each driving row to all reachable descendants or ancestors. The
	 * element type is joined as a normal table to that CTE, so the rest of the
	 * pipeline (declared fields, nested joins, sub-collections) expands the
	 * element type the same way it would for an {@link EntityCollection}.
	 */
	public record RecursiveCollection(
			String alias,
			TypeModel type,
			TableInfo tableInfo,
			List<QueryNode> children,
			FieldModel field,
			String parentAlias,
			String parentLinkColumn,
			String idColumn,
			SqlExpression recursionJoinCondition,
			Recursive.Direction direction) implements TableNode, FieldNode {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new RecursiveCollection(alias, type, tableInfo, List.copyOf(newChildren),
					field, parentAlias, parentLinkColumn, idColumn, recursionJoinCondition, direction);
		}
	}


	/**
	 * A one-to-many entity collection (LEFT JOIN).
	 * 
	 * <p>
	 * The foreign key column resides in the child table, referencing the
	 * primary key of the parent entity. Results are grouped by parent ID during
	 * row processing to build the collection.
	 */
	public record EntityCollection(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			FieldModel field, String parentAlias, String columnName, ForeignKeyInfo join, JdbcValueMapper valueMapper)
			implements TableNode, JoinMany {

		public static TableNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
				TypeModel componentType, TableInfo tableInfo, String parentAlias, ForeignKeyInfo join) {
			return new EntityCollection(alias, componentType, tableInfo, null, emptyFieldNode.field(), parentAlias,
					null, join, null);
		}

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EntityCollection(alias, type, tableInfo, List.copyOf(newChildren), field, parentAlias,
					columnName, join, valueMapper);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new EntityCollection(alias, type, tableInfo, children, field, parentAlias, columnName, newJoin,
					valueMapper);
		}

		public EntityCollection withValueMapper(JdbcValueMapper valueMapper) {
			return new EntityCollection(alias, type, tableInfo, children, field, parentAlias, columnName, join,
					valueMapper);
		}
	}
	public record TableInfo(
			String schemaName,
			String tableName) {
		public TableInfo {
			Objects.requireNonNull(tableName, "tableName");
		}

		public static TableInfo of(String tableName) {
			Objects.requireNonNull(tableName, "tableName");
			return new TableInfo(null, tableName);
		}

		public static TableInfo of(String schemaName, String tableName) {
			Objects.requireNonNull(tableName, "tableName");
			return new TableInfo("".equals(schemaName) ? null : schemaName, tableName);
		}

		@Override
		public final String toString() {
			return "TableInfo[" +
					(schemaName == null ? "" : "schemaName=" + schemaName + ", ") +
					"tableName=" + tableName + "]";
		}
	}

}
