package org.pojoquery.pipeline;

import java.util.List;
import java.util.Objects;

import org.pojoquery.JdbcValueMapper;
import org.pojoquery.SqlExpression;
import org.pojoquery.pipeline.querytree.TableInfo;
import org.pojoquery.typemodel.FieldModel;
import org.pojoquery.typemodel.TypeModel;

public class AbstractQueryTree {

	/**
	 * This is the improved structure for the querytree, strictly based on java properties.
	 * 
	 * An entity is a class mapped to a table.
	 * 
	 * Each java property transforms into one of:
	 * - ScalarValue: a primitive value or string (non-entity), a single column or
	 * SQL expression
	 * - EntityReference: a reference to another entity (many-to-one or one-to-one)
	 * - EntityCollection: a collection of entities (one-to-many)
	 * - ValueCollection: a collection or map of scalar values (non-entities) from a
	 * one-to-many join
	 * - JoinTableEntityCollection: a collection of entities through a join table
	 * (many-to-many)
	 * - JoinTableValueCollection: a collection of primitive values (non-entities)
	 * through a join table (many-to-many)
	 * - Embedding: an embedded entity
	 * - Transient: a field is not queried (not mapped to any column or join)
	 * 
	 * Single Table Inheritance adds Embeddings for superclasses and subclasses
	 * 
	 * Table per Subclass adds an EntityReference for its direct superclass and
	 * direct subclasses
	 * 
	 * Each of the non-scalar types (EntityReference, EntityCollection,
	 * JoinTableEntityCollection, Embedding) corresponds to a TableNode in the query
	 * tree, and can have child nodes for their properties.
	 */

	public sealed interface QueryNode
			permits TableNode, EmptyTableNode, EmptyFieldNode, FieldNode {
	}

	public sealed interface ScalarNode
			extends FieldNode
			permits PrimaryKeyField, ForeignKeyField, ScalarValue, JoinTableValueCollection {
		
	}

	public non-sealed interface PrimaryKeyField extends ScalarNode, Column {
		Boolean isAutoGenerated();
	}

	public non-sealed interface ForeignKeyField extends ScalarNode, Column {
	}

	public sealed interface TableNode
			extends QueryNode
			permits Embedding, RootNode, EntityNode, EntityCollection, JoinTableEntityCollection, TPSSubClassNode,
			TPSSuperClassNode {
		String alias();

		TypeModel type();

		TableInfo tableInfo();

		List<QueryNode> children();

		TableNode withChildren(List<? extends QueryNode> newChildren);
	}

	public non-sealed interface Embedding
			extends TableNode {
		String sourceAlias();
	}

	public record TPSSubClassNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			ForeignKeyInfo join, String parentAlias)
			implements TableNode, Join {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new TPSSubClassNode(alias, type, tableInfo, List.copyOf(newChildren), join, parentAlias);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new TPSSubClassNode(alias, type, tableInfo, children, newJoin, parentAlias);
		}
	}

	public record TPSSuperClassNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			ForeignKeyInfo join, String parentAlias)
			implements TableNode, Join {

		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new TPSSuperClassNode(alias, type, tableInfo, List.copyOf(newChildren), join, parentAlias);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new TPSSuperClassNode(alias, type, tableInfo, children, newJoin, parentAlias);
		}
	}

	// STINode = Single Table Inheritance node, represents a class in the STI
	// hierarchy. It has an alias and type, but shares the same table as its parent
	// (so no join).
	public interface STINode
			extends Embedding {
		Object discriminatorValue();

		String discriminatorColumn();
	}

	/**
	 * Represents a Java field/property mapping.
	 */
	public non-sealed interface FieldNode extends QueryNode {
		FieldModel field();
	}

	public non-sealed interface EntityNode extends FieldNode, TableNode {

	}

	/**
	 * Represents a database column in the current/parent table.
	 * Collections don't implement this because their FK is in the child table.
	 */
	public interface Column extends FieldNode {
		String columnName();

		Column withColumnName(String columnName);

		JdbcValueMapper valueMapper();

		public FieldNode withValueMapper(JdbcValueMapper valueMapper);
	}

	public non-sealed interface EmptyFieldNode extends QueryNode {
		FieldModel field();
	}

	public record EmptyTableNode(String alias, TypeModel type, TableInfo tableInfo) implements QueryNode {
	}

	public record RootNode(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children)
			implements TableNode {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new RootNode(alias, type, tableInfo, List.copyOf(newChildren));
		}

		public RootNode fromEmptyTableNode(EmptyTableNode empty, List<QueryNode> children) {
			return new RootNode(empty.alias, empty.type, empty.tableInfo, List.copyOf(children));
		}
	}

	public record EmbeddedEntity(String alias, TypeModel type, String sourceAlias, TableInfo tableInfo, List<QueryNode> children, FieldModel field, String fieldPrefix
		) implements Embedding, EntityNode {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EmbeddedEntity(alias, type, sourceAlias, tableInfo, List.copyOf(newChildren), field, fieldPrefix);
		}

		public static QueryNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias, TypeModel embeddedType, String sourceAlias, TableInfo tableInfo, String fieldPrefix) {
			return new EmbeddedEntity(alias, embeddedType, sourceAlias, tableInfo, null, emptyFieldNode.field(), fieldPrefix);
		}
	}

	public record ScalarValue(FieldModel field, String columnName, SqlExpression expression, JdbcValueMapper valueMapper) implements ScalarNode, Column {

		public ScalarValue withExpression(SqlExpression sql) {
			return new ScalarValue(field, columnName, sql, valueMapper);
		}

		public ScalarValue withValueMapper(JdbcValueMapper valueMapper) {
			return new ScalarValue(field, columnName, expression, valueMapper);
		}

		public ScalarValue withColumnName(String columnName) {
			System.out.println("Setting column name for field " + field.getName() + " to " + columnName);
			return new ScalarValue(field, columnName, expression, valueMapper);
		}

		public static QueryNode ofEmptyFieldNode(EmptyFieldNode emptyFieldNode) {
			return new ScalarValue(emptyFieldNode.field(), null, null, null);
		}

	}

	public record PrimaryKey(FieldModel field, String columnName, SqlExpression expression, Boolean isAutoGenerated, JdbcValueMapper valueMapper)
			implements PrimaryKeyField {
		
		public static PrimaryKey fromField(FieldModel field) {
			return new PrimaryKey(field, null, null, null, null);
		}
		
		public PrimaryKey withExpression(SqlExpression sql) {
			return new PrimaryKey(field, columnName, sql, isAutoGenerated, valueMapper);
		}

		public PrimaryKey setAutoGenerated(boolean b) {
			return new PrimaryKey(field, columnName, expression, b, valueMapper);
		}

		public PrimaryKey withValueMapper(JdbcValueMapper valueMapper) {
			return new PrimaryKey(field, columnName, expression, isAutoGenerated, valueMapper);
		}

		public PrimaryKey withColumnName(String columnName) {
			System.out.println("Setting column name for field " + field.getName() + " to " + columnName);

			return new PrimaryKey(field, columnName, expression, isAutoGenerated, valueMapper);
		}
	}

	public sealed interface Join permits JoinOne, JoinMany, TPSSuperClassNode, TPSSubClassNode {
		String parentAlias();

		ForeignKeyInfo join();

		QueryNode withJoin(ForeignKeyInfo newJoin);
	}

	public sealed interface JoinMany extends FieldNode, Join {
	}
	public sealed interface JoinOne extends Column, Join {
	}

	public record ValueCollection(FieldModel field, String alias, TypeModel componentType, TableInfo joinTable, String fetchColumn, String parentAlias, ForeignKeyInfo join, SqlExpression expression, JdbcValueMapper valueMapper) 
		implements JoinMany {

		public static ValueCollection fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias, TypeModel componentType, TableInfo joinTable, String fetchColumn, String parentAlias, ForeignKeyInfo join) {
			return new ValueCollection(emptyFieldNode.field(), alias, componentType, joinTable, fetchColumn, parentAlias, join, null, null);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new ValueCollection(field, alias, componentType, joinTable, fetchColumn, parentAlias, newJoin, expression, valueMapper);
		}

		public QueryNode withExpression(SqlExpression sql) {
			return new ValueCollection(field, alias, componentType, joinTable, fetchColumn, parentAlias, join, sql, valueMapper);
		}

		public ValueCollection withValueMapper(JdbcValueMapper valueMapper) {
			return new ValueCollection(field, alias, componentType, joinTable, fetchColumn, parentAlias, join, expression, valueMapper);
		}
	}

	public record JoinTableInfo(TableInfo tableInfo, String joinTableAlias) {
	}

	public record ForeignKeyInfo(TableInfo referringTable, String referringAlias, TableInfo targetTable,
			String targetAlias, FieldModel foreignKeyField, String fkColumnName, FieldModel idField,
			String idColumnName, SqlExpression joinCondition) {

		public ForeignKeyInfo {
			Objects.requireNonNull(idField, "idField must not be null");
		}

		public static ForeignKeyInfo fkInParent(TableInfo parentTable, String parentAlias, TableInfo childTable,
				String childAlias, FieldModel foreignKeyField, FieldModel idField) {
			return new ForeignKeyInfo(parentTable, parentAlias, childTable, childAlias, foreignKeyField, null, idField,
					null, null);
		}

		public static ForeignKeyInfo fkInChild(TableInfo parentTable, String parentAlias, TableInfo childTable,
				String childAlias, FieldModel idField) {
			return new ForeignKeyInfo(childTable, childAlias, parentTable, parentAlias, null, null, idField, null,
					null);
		}

		public ForeignKeyInfo withJoinCondition(SqlExpression joinCondition) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField,
					fkColumnName, idField, idColumnName, joinCondition);
		}

		public ForeignKeyInfo withFkColumnName(String fkColumnName) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField,
					fkColumnName, idField, idColumnName, joinCondition);
		}

		public ForeignKeyInfo withIdColumnName(String idColumnName) {
			return new ForeignKeyInfo(referringTable, referringAlias, targetTable, targetAlias, foreignKeyField,
					fkColumnName, idField, idColumnName, joinCondition);
		}
	}

	public record JoinTableJoin(JoinTableInfo joinTableInfo, ForeignKeyInfo parentKey, ForeignKeyInfo childKey) {

		public JoinTableJoin withJoinTableInfo(JoinTableInfo joinTableInfo) {
			return new JoinTableJoin(joinTableInfo, parentKey, childKey);
		}

		public JoinTableJoin withJoinForeignKeyInfo(ForeignKeyInfo parentKey, ForeignKeyInfo childKey) {
			return new JoinTableJoin(joinTableInfo, parentKey, childKey);
		}

	}

	public sealed interface HasJoinTableJoin {
		JoinTableJoin join();

		QueryNode withJoinTableJoin(JoinTableJoin joinTableJoin);
	}

	public record JoinTableEntityCollection(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			FieldModel field, JoinTableJoin join, String parentAlias, JdbcValueMapper valueMapper)
			implements TableNode, HasJoinTableJoin, FieldNode {

		public static QueryNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias, TypeModel componentType,
				TableInfo tableInfo, JoinTableJoin join, String parentAlias) {
			return new JoinTableEntityCollection(
					alias,
					componentType,
					tableInfo,
					null,
					emptyFieldNode.field(),
					join,
					parentAlias,
					null);
		}

		@Override
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new JoinTableEntityCollection(alias, type, tableInfo, List.copyOf(newChildren), field, join,
					parentAlias, valueMapper);
		}

		public JoinTableEntityCollection withJoinTableJoin(JoinTableJoin joinTableJoin) {
			return new JoinTableEntityCollection(alias, type, tableInfo, children, field, joinTableJoin, parentAlias, valueMapper);
		}

		public JoinTableEntityCollection withValueMapper(JdbcValueMapper valueMapper) {
			return new JoinTableEntityCollection(alias, type, tableInfo, children, field, join, parentAlias, valueMapper);
		}

	}

	public non-sealed interface JoinTableValueCollection extends ScalarNode, HasJoinTableJoin {
		String[] fieldsToSelect();

		JdbcValueMapper valueMapper();
	}

	// EntityReference
	// EntityCollection
	// ValueCollection = EntityCollection with projection
	// JoinTableEntityCollection
	// JoinTableValueCollection = JoinTableEntityCollection with projection
	// Embedding

	// Superclasses zijn EntityReference of Embedded

	public record EmptyFieldNodeImpl(FieldModel field) implements EmptyFieldNode {
	}

	public record EntityReference(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			FieldModel field, String parentAlias, String columnName, ForeignKeyInfo join, JdbcValueMapper valueMapper)
			implements EntityNode, JoinOne {
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EntityReference(alias, type, tableInfo, List.copyOf(newChildren), field, parentAlias, columnName,
					join, valueMapper);
		}

		public static EntityReference fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
				TableInfo determinTableInfo, FieldModel field, String parentAlias, ForeignKeyInfo join) {
			return new EntityReference(alias, field.getType(), determinTableInfo, null, field, parentAlias, null, join, null);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, newJoin.fkColumnName,
					newJoin, valueMapper);
		}

		public EntityReference withValueMapper(JdbcValueMapper valueMapper) {
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, columnName, join, valueMapper);
		}

		public EntityReference withColumnName(String columnName) {
			System.out.println("Setting column name for field " + field.getName() + " to " + columnName);
			return new EntityReference(alias, type, tableInfo, children, field, parentAlias, columnName, join, valueMapper);
		}
	}

	public record EntityCollection(String alias, TypeModel type, TableInfo tableInfo, List<QueryNode> children,
			FieldModel field, String parentAlias, String columnName, ForeignKeyInfo join, JdbcValueMapper valueMapper)
			implements TableNode, JoinMany {
		
		public static TableNode fromEmptyFieldNode(EmptyFieldNode emptyFieldNode, String alias,
			TypeModel componentType, TableInfo tableInfo, String parentAlias, ForeignKeyInfo join) {
				return new EntityCollection(alias, componentType, tableInfo, null, emptyFieldNode.field(), parentAlias,
				null, join, null);
		}
					
		public TableNode withChildren(List<? extends QueryNode> newChildren) {
			return new EntityCollection(alias, type, tableInfo, List.copyOf(newChildren), field, parentAlias,
					columnName, join, valueMapper);
		}

		public QueryNode withJoin(ForeignKeyInfo newJoin) {
			return new EntityCollection(alias, type, tableInfo, children, field, parentAlias, columnName, newJoin, valueMapper);
		}

		public EntityCollection withValueMapper(JdbcValueMapper valueMapper) {
			return new EntityCollection(alias, type, tableInfo, children, field, parentAlias, columnName, join, valueMapper);
		}
	}

}
