package org.pojoquery.pipeline;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.pojoquery.DB;
import org.pojoquery.pipeline.AbstractQueryTree.Column;
import org.pojoquery.pipeline.AbstractQueryTree.EntityReference;
import org.pojoquery.pipeline.AbstractQueryTree.PrimaryKey;
import org.pojoquery.pipeline.AbstractQueryTree.QueryNode;
import org.pojoquery.pipeline.AbstractQueryTree.RootNode;
import org.pojoquery.pipeline.AbstractQueryTree.ScalarValue;
import org.pojoquery.typemodel.FieldModel;
import org.pojoquery.typemodel.ReflectionFieldModel;

public class AQTCascadingUpdater {
	record FieldValues(Map<String, Object> values, Map<String, Object> idValues, String autoGenIdField) {}

	public static <PK> PK insert(Connection conn, Object entity) {
		RootNode tree = AQTTransformer.buildQueryTreeForType(entity.getClass());
		FieldValues fieldValues = collectFields(tree, entity);
		// Assert.assertEquals("Jane Austen", fieldValues.values().get("name"));
		// Assert.assertNull(fieldValues.idValues().get("id"));
		PK generatedId = DB.insert(conn, tree.tableInfo().schemaName(), tree.tableInfo().tableName(), fieldValues.values());
		if (fieldValues.autoGenIdField() != null) {
			setFieldValue(entity, tree.children().stream()
				.filter(child -> child instanceof PrimaryKey pk && pk.field().getName().equals(fieldValues.autoGenIdField()))
				.map(child -> ((PrimaryKey) child).field())
				.findFirst()
				.orElseThrow(() -> new IllegalStateException("Auto-generated ID field '" + fieldValues.autoGenIdField() + "' not found in query tree")), 
				generatedId
			);
		}
		return generatedId;
	}

	private static FieldValues collectFields(RootNode tree, Object entity) {
		Map<String, Object> values = new LinkedHashMap<>();
		Map<String, Object> idValues = new LinkedHashMap<>();
		String autoGenIdField = null;

		for (QueryNode children : tree.children()) {
			if (children instanceof Column fieldNode && fieldNode.field() != null) {
				String fieldName = fieldNode.field().getName();
				String columnName = fieldNode.columnName();
				Object value = getFieldValue(entity, fieldNode.field());

				if (fieldNode instanceof PrimaryKey pk) {
					if (pk.isAutoGenerated()) {
						if (value != null) {
							throw new IllegalStateException("Auto-generated ID field '" + fieldName + "' should not have a value");
						}
						autoGenIdField = fieldName;
					} else {
						if (value == null) {
							throw new IllegalStateException("ID field '" + fieldName + "' must have a value");
						}
					}
					idValues.put(columnName, value);
				} else if (fieldNode instanceof EntityReference entityRef) {
					// For entity references, we want to collect the ID value of the referenced entity
					if (value != null) {
						FieldModel referencedIdField = entityRef.children().stream()
							.filter(child -> child instanceof PrimaryKey)
							.map(child -> ((PrimaryKey) child).field())
							.findFirst()
							.orElseThrow(() -> new IllegalStateException("Referenced entity in field '" + fieldName + "' does not have an ID field"));
						Object referencedIdValue = getFieldValue(value, referencedIdField);
						if (referencedIdValue == null) {
							throw new IllegalStateException("Referenced entity in field '" + fieldName + "' has null ID value");
						}
						values.put(columnName, referencedIdValue);
					} else {
						values.put(columnName, null);
					}
				} else if (fieldNode instanceof ScalarValue) {
					values.put(columnName, value);
				}
			}
		}
		return new FieldValues(values, idValues, autoGenIdField);
	}

	private static Object getFieldValue(Object entity, FieldModel fieldModel) {
		try {
			Field field = ((ReflectionFieldModel)fieldModel).getReflectionField();
			field.setAccessible(true);
			return field.get(entity);
		} catch (IllegalAccessException e) {
			return null;
		}
	}

	private static void setFieldValue(Object entity, FieldModel fieldModel, Object value) {
		try {
			Field field = ((ReflectionFieldModel)fieldModel).getReflectionField();
			field.setAccessible(true);
			field.set(entity, value);
		} catch (IllegalAccessException e) {
			throw new RuntimeException(e);
		}
	}

}
