package nl.pojoquery.integrationtest.db;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;

import org.hsqldb.jdbc.JDBCDataSource;

import nl.pojoquery.DB;
import nl.pojoquery.DbContext;
import nl.pojoquery.DbContext.QuoteStyle;
import nl.pojoquery.SqlExpression;

public class HSQLDatabases {
	
	public static void main(String[] args) throws Exception {
		DbContext.getDefault().setQuoteStyle(QuoteStyle.ANSI);
		
		try (Connection c = DriverManager.getConnection("jdbc:hsqldb:mem:test", "SA", "")) {
			DB.executeDDL(c, """
				CREATE TABLE "t2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, "name" VARCHAR(20))
				""");
			
			DB.insert(c, "t2", Map.of("name", "henk"));
			
			System.out.println(DB.queryRows(c, SqlExpression.sql("""
				SELECT * FROM "t2"
				""")));
			List<Map<String, Object>> tables = DB.queryRows(c, SqlExpression.sql("""
				SELECT * FROM INFORMATION_SCHEMA.TABLES
				"""));
			System.out.println(tables.get(0).keySet());
			for(Map<String, Object> row : tables) {
				System.out.println(row.get("TABLE_SCHEMA") + "." + row.get("TABLE_NAME"));
			}
			
			System.out.println("_____ dump ______");
			Path dumpfile = Paths.get(".", "dump.db");
			dumpfile.toFile().delete();
			
			DB.executeDDL(c, """
				PERFORM EXPORT SCRIPT FOR DATABASE STRUCTURE WITH COLUMN NAMES TO '__FILE__' 
				""".replace("__FILE__", dumpfile.toString())); 
			
			Files.copy(dumpfile, System.out);
		}
	}

	public static DataSource getDataSource() {
		JDBCDataSource dataSource = new JDBCDataSource();
		dataSource.setUrl("jdbc:hsqldb:mem:test");
		dataSource.setUser("SA");
		dataSource.setPassword("");
		return dataSource;
	}
}
